### ISSUE TITLE
How to disable converting block level elements?

### ISSUE THREAD

**Issue by andrewhavens** [vmg/redcarpet#102]
I'm using Red Carpet in a way that may be different than most use cases. I really only care about rendering inline elements, not block level elements. For example, a string like `#hashtag` is converted into `<h1>hashtag</h1>`. I want to disable this feature, but overriding the `header` method in my custom renderer is not enough. I don't have access to the original text:

```
def header(text, header_level)
  text #only returns 'hashtag' not '#hashtag'
end
```

Is there a way to disable block level parsing all together? Or is there a way to get the original text from within the `header` method?

**Comment by hakunin** [comment]
Anyone worked this one around? I am thinking of replacing hashtags with placeholders and putting them back when markdown is done as a very generic workaround.

Any ideas about how this can be simplified? The JS Markdown formatter we use doesn't have this issue.
