### ISSUE TITLE
Aligned Labelled Lists

### ISSUE THREAD

**Issue by trans** [vmg/redcarpet#108]
The only thing that keeps me using rdoc instead of markdown for most of my project documents is the lack of aligned labelled lists. e.g.

```
Label1:: Some description of label 1.
Label2:: Some description of label 2.
```

In RDoc this produces a two-column table, with a special class so in can be distinguished from regular tables. Usage is not uncommon, for example: https://github.com/jimwise/rulog/blob/master/README.rdoc. I use it myself in COPYING.rdoc files, e.g. https://github.com/rubyworks/ansi/blob/master/COPYING.rdoc.

I would really like to see markdown support something comparable, if not the exact same syntax.

**Comment by nschneid** [comment]
+1 for definition lists. I use these all the time in technical documentation.

**Comment by gerwitz** [comment]
+1 for the PHP Markdown Extra syntax

**Comment by robin850** [comment]
Hello,

Sorry but as you might have noticed, this project has pretty limited resources so adding new features is not a priority as this will increase the maintainance burden.

Thus, we are going to give this ticket a close. We might consider reopening it in the future if it makes sense.

Thank you very much for your proposal and understanding.
