### ISSUE TITLE
no_intra_emphasis should also ignore patterns such as h_{t}

### ISSUE THREAD

**Issue by cboettig** [vmg/redcarpet#130]
I am having difficulty with redcarpet when including mathjax equations.  The no_intra_emphasis usually does the trick to avoid underscores such as `\\( h_t \\)` becoming `\( h<em>t \)` when it should be left as something mathjax can parse.  Unfortunately, and underscore followed by a bracket instead of a letter, such as `h_{t+1}` does get converted.  It seems like the expected behavior for no_intra_emphasis should insist on a whitespace followed by an underscore to begin `<em>` and a underscore followed only by a whitespace to end `</em>`.  Is this possible?  Am I missing a more natural work-around to be able to include mathjax syntax in markdown files?  Thanks much!

**Comment by zerocool4u2** [comment]
i know this is a little old but, i came to the same conclusion that @lsegal on use de block-code tag, that work pretty well, but still bugs me can just use a $ $ block. After digging a little i found out that the span tags are applied before the paragraph function, so i check the pattern if starts and ends with $$ and do this ```ActionView::Base.full_sanitizer.sanitize(%(#{text}).gsub("<u>", "_"))``` the actionView helper will clean any tags that could be generated that i forgot and the gsub restores the underscore, i'm gonna do the same for the inline math, do you find any other cases that makes fail the LaTeX code? if this one the only case i'm gonna just use gsub, regards

**Comment by oblitum** [comment]
@zerocool4u2 read this http://nosubstance.me/post/a-great-toolset-for-static-blogging/.

This is a problem solved already, by using other markdown parsers. If you still wish to stick with Jekyll, it currently adopts Kramdown by default now, which supports MathJax and related well out-of-the-box.
