### ISSUE TITLE
How to ignore the html comments <!-- comment -->.

### ISSUE THREAD

**Issue by gsonicis** [vmg/redcarpet#134]
I am using redcarpet (2.1.1) and Rails 3.2.

The problem is that HTML comments tag code are not executing on view section.   
I have seen  on http://markdownr.com/ html comments code are working.

Is there any markdown options to working the HTML comment tag code on view?

**Comment by eonist** [comment]
Found a better solution: {{ content | remove_first: '&lt;!--more--&gt;', '' }}

Now you can use  as a global excerpt_separator in config.

You can use http://www.freeformatter.com/html-escape.html#ad-output to escape any word you want.
