### ISSUE TITLE
Uninitialized constant: Redcarpet::Render::StripDown

### ISSUE THREAD

**Issue by timscott** [vmg/redcarpet#138]
I get this error using 2.1.1.  I check the gem and it has `/lib/redcarpet/render_strip.rb`.  In the same (helper) file where I get this error I am able to call `Redcarpet::Render::HTML.new` without any error.  At the top of the file is:

```
require 'redcarpet'
require 'nokogiri'
```

I guess I don't know enough about how gems work to know how this can be, but it seems like an error in the gem.

**Comment by cesswairimu** [comment]
i have this in one of my controllers
def show
    @achievement = Achievement.find(params[:id])
   @description=Redcarpet::Markdown.new(Redcarpet::Render::HTML).render(@achievement.description)
  end
when i go to the show page i get 'uninitialized constant AchievementsController::Redcarpet' error

**Comment by coderade** [comment]
@cesswairimu Normally restart the server will solve this issue. That is my case.

There is a thread about this on the Stackoverflow that we can see on this [link](https://stackoverflow.com/questions/14670184/rails-redcarpet-uninitialized-constant-redcarpetrender-when-used-in-applica).

**Comment by thebravoman** [comment]
Stumbled upon this in rails 6

```
  > uninitialized constant Redcarpet::Render::StripDown
          
            app/views/group_user_mailer/user_enrolled_in_group.text.erb, line 1
            -------------------------------------------------------------------
          
            ``` ruby
            >   1   <% renderer = Redcarpet::Render::StripDown.new %>
                2   <% markdown = Redcarpet::Markdown.new(renderer, autolink: true) %>
                3   <%= markdown.render(@email_content).text %>
            ```

```
Restarting the server is not working. Restarting spring also. In the tests the is also this error.

It works perfectly fine with Redcarpet::Render::HTML.new as a rendered
