### ISSUE TITLE
Allow different types of ordered lists (numbers, letters, roman numerals)

### ISSUE THREAD

**Issue by patcon** [vmg/redcarpet#152]
This works for numbered lists:

```
1. item 1
1. item 2
1. item 3
```

Gives:
1. item 1
2. item 2
3. item 3

It would be great if this could work similarly, particularly for docs with nested lists where you want to differentiate the indent levels a bit:

```
a. item 1
a. item 2
a. item 3

i. item 1
i. item 2
i. item 3
```

**Comment by robin850** [comment]
Hello,

Sorry but as you might have noticed, this project has pretty limited resources so adding new features is not a priority as this will increase the maintainance burden.

Thus, we are going to give this ticket a close. We might consider reopening it in the future if it makes sense.

Thank you very much for your proposal and understanding.
