### ISSUE TITLE
Add an option to leave hard tabs alone in code blocks

### ISSUE THREAD

**Issue by jneen** [vmg/redcarpet#153]
This is causing a bit of trouble when trying to syntax-highlight Makefile syntax in Rouge, since the Makefile lexer correctly expects blocks to be indented with hard tabs.

An option to pass the `block_code` handler the raw string with the hard tabs in it would be wonderful.

**Comment by ginzel** [comment]
@vmg Please, where is exactly the weakness/limitation of Markdown specification about indentation/tabs?
