### ISSUE TITLE
octopress-like behavior of backticks

### ISSUE THREAD

**Issue by LeonB** [vmg/redcarpet#187]
I really like the fenced [code block thingy of Octopress](http://octopress.org/docs/plugins/backtick-codeblock/):

``````
     ``` ruby Example code
    do_somethin()
    ```
``````

Which generates a figure & figcaption element.

Is this a feature that could be added to redcarpet? If not, would it be possible to extend redcarpet myself to add this behavior?

**Comment by chitsaou** [comment]
Hi there, I have created an HTML::Pipeline filter to do this. If you are using Jekyll you can use it painlessly. See https://github.com/chitsaou/markdown-highlight-extended-filter
