### ISSUE TITLE
uninitialized constant Redcarpet::Render when used in ApplicationHelper

### ISSUE THREAD

**Issue by sunnyrjuneja** [vmg/redcarpet#195]
I'm following along the RailsCasts episode for [Syntax Highlighting Revised](http://railscasts.com/episodes/207-syntax-highlighting-revised). I updated my ApplicationHelper to look like so:

```
require 'redcarpet'

module ApplicationHelper
  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer:language)
    end
  end

  def markdown(text)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end
end
```

However, my web app returns 

```
Routing Error

uninitialized constant Redcarpet::Render

Try running rake routes for more information on available routes. 
```

I'm using Rails 3.2.11 and Redcarpet responds fine in rails console. I've originally didn't include `require 'redcarpet'` but I followed the instructions on [here](http://stackoverflow.com/questions/7085053/unitialized-constant-in-model) but it didn't help.

**Comment by BrittanyOh** [comment]
I've tried that and it doesn't work for me as well as for another person I've seen with the same issue

**Comment by sunnyrjuneja** [comment]
@BrittanyOh If you can create a repo and reproduce the problem, I would be happy to try to help you. I'm not a maintainer (or a contributor to the repo for that matter) but I would be happy to give it a look.
