### ISSUE TITLE
support php-markdown-extra abbreviations

### ISSUE THREAD

**Issue by sunaku** [vmg/redcarpet#197]
Hello,

Please add support for [abbreviations like php-markdown-extra](http://michelf.ca/projects/php-markdown/extra/#abbr).

Thanks for your consideration.

**Comment by brandonweiss** [comment]
I made an [extension for Redcarpet](/brandonweiss/redcarpet-abbreviations) that renders abbreviations.

**Comment by sunaku** [comment]
:+1: Hooray! Thank you @brandonweiss :bow:

**Comment by ttimsmith** [comment]
I'd also love to see this added.

**Comment by robin850** [comment]
Hello,

Sorry but as you might have noticed, this project has pretty limited resources so adding new features is not a priority as this will increase the maintainance burden.

Thus, we are going to give this ticket a close. We might consider reopening it in the future if it makes sense.

Thank you very much for your proposal and understanding.
