### ISSUE TITLE
Allow retrieving the options used for a renderer

### ISSUE THREAD

**Issue by aprescott** [vmg/redcarpet#205]
Sometimes within custom renderer methods like `header(text, level)` for custom renderers, you need to call `Redcarpet::Markdown.new(SomeRenderer).render` because there is no `super` (see #51), but there's no way of getting the options passed to the original instance that has had `render` called on it, meaning there's potential duplication.

A somewhat contrived example to show what I mean:

```ruby
Redcarpet::Markdown.new(CustomRenderer, no_intra_emphasis: true)
```

Where `CustomRenderer` might look like:

```ruby
class CustomRenderer < Redcarpet::Render::SmartyHTML
  def header(text, level)
    if level > 3
      # no super method, so this, with duplicated no_intra_emphasis flag
      original = Redcarpet::Markdown.new(Redcarpet::Render::SmartyHTML, no_intra_emphasis: true)
      return original.render("#"*3 + " " + text)
    end

    %Q{<h#{level} class="demonstrating">#{text}</h#{level}>}
  end
end
```

Having a way to grab the options `{ no_intra_emphasis: true }` in the custom renderer would make this a little easier, although fixing #51 by allowing super / returning the original value would probably make this mostly unneeded.

**Comment by danmichaelson** [comment]
A workaround is to define your own initializer (which can call super). Then store a copy of the options in an instance variable.

    class CustomRenderer < Redcarpet::Render::SmartyHTML

      def initialize(options = {})
        @options = options
        super(options)
      end

      def header(text, level)
        # You can access @options here
      end

    end

**Comment by robin850** [comment]
This has been opened for a loooong time but this is now implemented, this will be in the next Redcarpet release, thanks for the proposal ! :-)
