### ISSUE TITLE
Is there a way to add css classes to markdown?

### ISSUE THREAD

**Issue by firedev** [vmg/redcarpet#306]
Is there a way to add css classes to redcarpet markdown? Something like this would work:

```
![](/image.jpg){.callout}
```

**Comment by yous** [comment]
It would be nice if we add Maruku-style attribute lists! We can easily add fixed `width` and `height` for `img`, `target` for `a`, or additional `data-*` things without rewriting whole HTML tags. Also adding `id` or `name` which will be used as an anchor is going to be easily done without adding additional `a` tag.

**Comment by IrsyadAdl** [comment]
This is not working

**Comment by robin850** [comment]
Hi there !

Giving it more thoughts, I will give this a close ; I understand that this can be a pretty interesting feature but this is too much diverging from the original purpose of Markdown. It's still possible to customize the output through custom render objects but no on an element basis.

Thanks for the proposal anyway guys ! :heart:

**Comment by E1000y** [comment]
trying to center an image with theses tools but won't work
