### ISSUE TITLE
Consider using Hoedown

### ISSUE THREAD

**Issue by devinus** [vmg/redcarpet#312]
I have revived Sundown into an improved library called Hoedown!

https://github.com/hoedown/hoedown

Here, I merged long languishing pull requests from Sundown, merged almost every improvement from Redcarpet[^1], merged improvements from Rinku and Houdini, greatly improved and standardized the API, and fixed [many potential bugs](https://gist.github.com/devinus/30b6df78d96eb9f06d33).

Full list of changes: https://github.com/hoedown/hoedown/compare/vmg:master...master

Sundown had a rich [collection of bindings](https://github.com/vmg/sundown#bindings) and it would truly be a shame if we couldn't all benefit from a single library in the future.

[^1]: The _only_ improvement from Redcarpet I couldn't accept was the GitHub style TOC links. While I'd love to add it, Redcarpet uses "ruby.h" to accomplish this.

**Comment by deckar01** [comment]
> we would change our API so we would have to release a 4.0.0 but yet again

I don't think this is a real con. If you break backwards compatibility, you bump the major version and life goes on. As a developer, I love it when major version bumps don't require major refactors to upgrade.

> I think it would be very hard to add [regular expressions] in C.

There are regex libraries for C.

> we are going to ship with 4.0.0 ... a new API to create our own extensions and let people do the exact same thing

Maybe that is something Hoedown would like to work towards also.

**Comment by robin850** [comment]
As Hoedown is no longer maintained and as relying on the Ruby API sparingly might be useful, I'm giving this a close. Thanks.
