### ISSUE TITLE
Task lists?

### ISSUE THREAD

**Issue by buotex** [vmg/redcarpet#329]
Hi, 
as I'm using redcarpet to render a static blog with, I wanted to know if there's any possibility to use task lists (https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments) when doing so.

**Comment by lifeiscontent** [comment]
@mattr- when will it be?

**Comment by robin850** [comment]
Actually I'm not sure this will ever be implemented in vanilla Redcarpet, this is pretty straightforward to implement:

~~~ruby
class CustomRender < Redcarpet::Render::HTML
  def list_item(text, list_type)
    if text.start_with?("[x]", "[X]")
      text[0..2] = %(<input type="checkbox" checked="checked">)
    elsif text.start_with?("[ ]")
      text[0..2] = %(<input type="checkbox">)
    end

    %(<li>#{text}</li>)
  end
end
~~~
