### ISSUE TITLE
Indentention problem in code blocks

### ISSUE THREAD

**Issue by novohispano** [vmg/redcarpet#346]
Redcarpet is not parsing the codeblocks properly.

This is my parser.

``` ruby
class Parser
  class HTMLRuby < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end

  def self.markdown_to_html(content)
    renderer = HTMLRuby.new(hard_wrap: true, filter_html: true)
    options  = {
      autolink:           true,
      no_intra_emphasis:  true,
      fenced_code_blocks: true,
      lax_html_blocks:    true,
      strikethrough:      true,
      superscript:        true
    }

    Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end
end
```

This is my view.

``` erb
<h1><%= @page.title %></h1>
<p><%= raw Parser.markdown_to_html(@page.content) %></p>
```

This is the output.

![screen shot 2014-01-31 at 5 19 11 pm](https://f.cloud.github.com/assets/1654034/2056261/8637692e-8ad6-11e3-8c3b-26aeb2beef92.png)

This is the original markdown.

![screen shot 2014-01-31 at 5 28 43 pm](https://f.cloud.github.com/assets/1654034/2056307/d8ed5204-8ad7-11e3-83c1-284007f8cc3d.png)

**Comment by cycorld** [comment]
The solution is using "~" for "=" in HAML.
