### ISSUE TITLE
{% highlight js %} followed by <div> enclosing <img> causing markdown between them not to be processed

### ISSUE THREAD

**Issue by Xitalogy** [vmg/redcarpet#365]
Here is my markdown, processed with redcarpet in Jekyll.  I am using Pygments as my syntax highlighter for code.  The markdown between the {% highlight js %} ... {% endhighlight %} and the &lt;div>&lt;img ...>&lt;/div> tag is not being processed - it just outputs it as if it were text.  If I get rid of the &lt;img> inside the &lt;div> it works just fine:

```

---
layout: post
title:  "RedCarpet Markdown Test"
date:   2014-04-02 12:12:12
categories: test

---

{% highlight js %}
function myfunc(x) {
    x += 5;
    return x;
}
{% endhighlight %}

### This is a Markdown Header

This is some markdown text with an inline code block: `var v = myFunc(10)`.  This markdown *is not* properly processed.

<div>
    <img style="width: 640px;" src="/images/delegate_based/constructor_simplified.png" alt="Constructor Diagram" />
</div>

### This is a Markdown Header

This is some markdown text with an inline code block: `var v = myFunc(10)`.  This markdown *is* properly processed.
```

**Comment by robin850** [comment]
Hello there,

Trying with a fresh Jekyll install (version 4.2.0) with the provided Markdown in the original post, everything works as expected. I don't know whether it was a problem on our side or if it's been fixed on the Jekyll one.

Anyway, I'm giving this a close. Thanks for reporting.
