### ISSUE TITLE
GitHub-like todo lists?

### ISSUE THREAD

**Issue by siadat** [vmg/redcarpet#379]
`redcarpet` is mentioned in GitHub's blog as what they use to render markdown files. I tried to create a list of todos with checkboxes as described in 
https://github.com/blog/1825-task-lists-in-all-markdown-documents, but didn't get the expected result. Am I doing something wrong or `recarpet` doesn't support GFM-style todo lists?

**Comment by westurner** [comment]
see also: https://github.com/vmg/redcarpet/issues/329#issuecomment-177210626
