### ISSUE TITLE
TOC header anchor generator doesn't replace dots

### ISSUE THREAD

**Issue by olivierlacan** [vmg/redcarpet#385]
This is sort of a minor aesthetic issue, but generally I feel like any heading text being processed for a TOC header should follow the kind of conversion that `ActiveSupport::Inflector#parameterize` does since it's going to end up in a URL:

``` ruby
parameterize "## 1. Commit your code in your feature branch."
=> "1-commit-your-code-in-your-feature-branch"
```

However this is how Redcarpet currently handles the same string:

``` ruby
markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML_TOC, with_toc_data: true)
=> #<Redcarpet::Markdown:0x007fb013172d28 @renderer=#<Redcarpet::Render::HTML_TOC:0x007fb013172d50>>
markdown.render "## 1. Commit your code in your feature branch."
=> "<ul>\n<li>\n<a href=\"#1.-commit-your-code-in-your-feature-branch.\">1. Commit your code in your feature branch.</a>\n</li>\n</ul>\n"

```

Seems like a simple regex update inside of [header_anchor](https://github.com/vmg/redcarpet/blob/64f717e23508ac76581691aaf94d0b55207cc144/ext/redcarpet/html.c#L272) would do the trick. It currently uses: `<\\/?[^>]*>`

This is the regex that [`parameterize`](https://github.com/rails/rails/blob/e20dd73df42d63b206d221e2258cc6dc7b1e6068/activesupport/lib/active_support/inflector/transliterate.rb#L85) uses: `/[^a-z0-9\-_]+/i`

C isn't my strong suit, but I can try to provide a PR for this if it seems sane.

**Comment by GoldAtomFussio** [comment]
#493 

> ["loadatomelectronneutronprotontodo"`load`](loadatomfussionelectron)

**Comment by KarolineCat** [comment]
> This is sort of a minor aesthetic issue, but generally I feel like any heading text being processed for a TOC header should follow the kind of conversion that `ActiveSupport::Inflector#parameterize` does since it's going to end up in a URL:
> 
> ```ruby
> parameterize "## 1. Commit your code in your feature branch."
> => "1-commit-your-code-in-your-feature-branch"
> ```
> 
> However this is how Redcarpet currently handles the same string:
> 
> ```ruby
> markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML_TOC, with_toc_data: true)
> => #<Redcarpet::Markdown:0x007fb013172d28 @renderer=#<Redcarpet::Render::HTML_TOC:0x007fb013172d50>>
> markdown.render "## 1. Commit your code in your feature branch."
> => "<ul>\n<li>\n<a href=\"#1.-commit-your-code-in-your-feature-branch.\">1. Commit your code in your feature branch.</a>\n</li>\n</ul>\n"
> ```
> 
> Seems like a simple regex update inside of [header_anchor](https://github.com/vmg/redcarpet/blob/64f717e23508ac76581691aaf94d0b55207cc144/ext/redcarpet/html.c#L272) would do the trick. It currently uses: `<\\/?[^>]*>`
> 
> This is the regex that [`parameterize`](https://github.com/rails/rails/blob/e20dd73df42d63b206d221e2258cc6dc7b1e6068/activesupport/lib/active_support/inflector/transliterate.rb#L85) uses: `/[^a-z0-9\-_]+/i`
> 
> C isn't my strong suit, but I can try to provide a PR for this if it seems sane.
