### ISSUE TITLE
Is the behavior of footnote link text correct?

### ISSUE THREAD

**Issue by namusyaka** [vmg/redcarpet#393]
I tried out the following code.

``` ruby
     markdown = <<-MD
 This is a footnote.[^7]

 [^7]: It provides additional information.
     MD

     html = <<-HTML
 <p>This is a footnote.<sup id="fnref7"><a href="#fn7" rel="footnote">7</a></sup></p>

 <div class="footnotes">
 <hr>
 <ol>

 <li id="fn7">
 <p>It provides additional information.&nbsp;<a href="#fnref7" rev="footnote">&#8617;</a></p>
 </li>

 </ol>
 </div>
     HTML
     renderer = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :footnotes => true)
     output = renderer.render(markdown)
     assert_equal html, output # false. This result, all 7 will be 1.
```

Is this the correct behavior?
If not, I'm going to send the pull request about the issue.

**Comment by robin850** [comment]
Hello there,

As you might have noticed, this project has pretty limited resources. Given that this use case seems not so common, I'm giving this a close.

Re-reading the story, I really feel like there should be a way for you to implement a custom render that memorize the footnote of previous invocations and generate the footnote number accordingly.

I'm giving this a close ; thanks !
