### ISSUE TITLE
Ability to create nested tables using markdown

### ISSUE THREAD

**Issue by hussainanjar** [vmg/redcarpet#394]
It will be nice to be able to create nested tables using markdown specially to show parameter descriptions of complex JSON objects.

**Comment by rawrgulmuffins** [comment]
A use case that I like is showing tasks in a project (for a work structure breakdown) I have things like


| task | 
|----|
| /status page |
|     * Connect to Rabbitmq |
|     * Connect to Celery Cluster |
|     * Connect to Redis cluster |

And I'd love to be able to show when something is a sub task of a larger task.

**Comment by metaspook** [comment]
> A use case that I like is showing tasks in a project (for a work structure breakdown) I have things like
> 
> task
> /status page
> * Connect to Rabbitmq
> * Connect to Celery Cluster
> * Connect to Redis cluster
> And I'd love to be able to show when something is a sub task of a larger task.
> 
> In this particular case my team just knows that stars mean that a task is a sub task of the first one without stars.

Bro how did you make table with single header? I need it
