### ISSUE TITLE
Markdown parsing error for Chinese Text

### ISSUE THREAD

**Issue by qiansen1386** [vmg/redcarpet#397]
If we break the line for each sentence, then the lib will add a white space after the sentence period, which should not happen for Chinese context, As the mark itself contains enough spaces by designed. However many people will break a line for each sentence in editor to make it more readable, just like what we do in English.

For example, there is some dummy text, each sentence a line, just to simulate how people usually type:

```
工拉根又这证性建干式进九离，强无北原得F书雨方适。
片真我即积证导主打，总片性样千斗下公观，地3指辰文露茅。
观前全听马周速它状张，题半素根话质难所压，复主L器强十你折。
提支多果做下斯化精王照器更，办且间每员两虚雨包众。
科称观者入原切何空机，转重干流广济将土生，林众1连红四学取。
率是非的律热权构手反，运活整个全代给把型小，速土V护五属积准。
增便养王太以参么，于非七本回导，代技7完战文。
京族石派置技动战何，系战压反叫少应，度声2虚时起电。
术听四想在信个基取，然去步律太转按都，究豆该吩以杨军。
```

And you ll get 

工拉根又这证性建干式进九离，强无北原得F书雨方适。 片真我即积证导主打，总片性样千斗下公观，地3指辰文露茅。 观前全听马周速它状张，题半素根话质难所压，复主L器强十你折。 提支多果做下斯化精王照器更，办且间每员两虚雨包众。 科称观者入原切何空机，转重干流广济将土生，林众1连红四学取。 率是非的律热权构手反，运活整个全代给把型小，速土V护五属积准。 增便养王太以参么，于非七本回导，代技7完战文。 京族石派置技动战何，系战压反叫少应，度声2虚时起电。 术听四想在信个基取，然去步律太转按都，究豆该吩以杨军。

Maybe it is because Markdown is designed for Latin-characters.  We always add space between each words in this context. However that will not work for East Asia Languages

How about just recognize the symbols "。" and "，", they are period and comma in Chinese-style.

**Comment by robin850** [comment]
Hello there,

Sorry for the very late answer. For sure, Redcarpet doesn't deal well with non-ASCII stuff in general but I'm not sure that's something we should enable or support out of box.

Maybe in this case, you can rely on a custom render object to make things work as you wish. Something along these lines:

~~~ruby
class CustomRender < Redcarpet::Render::HTML
  def preprocess(document)
    document.lines.map { |line|
      line.end_with?("。\n") ? line.rstrip : line
    }.join("")
  end
end
~~~

I'm giving this a close ; thanks.
