### ISSUE TITLE
link_attributes for autolink

### ISSUE THREAD

**Issue by explodi** [vmg/redcarpet#398]
It seems the :link_attributes option is not working for autolinks. It would be very useful to add a "nofollow" tag to those links to prevent link building.

i use :link_attributes=> {:rel=>"nofollow"} and :autolink => true with no luck :(

**Comment by EddieOne** [comment]
Is it possible to make it optional, like the following?

```
def markdown_format(text, nofollow = false)
    renderer = Redcarpet::Render::HTML.new(
      filter_html: true,
      no_links: false
    )
    renderer[:link_attributes] = { rel: 'nofollow' } if nofollow
```
