### ISSUE TITLE
excerpt_separator <!--more--> is rendered as text

### ISSUE THREAD

**Issue by fkostadinov** [vmg/redcarpet#415]
When I specify a dedicated excerpt_separator such as  in my _config.yml file, then the following happens:
1. In my front-page index.html file, the excerpts are correctly cut off immediately at .
2. In the blog post itself,  does actually appear as textual content in the middle of the text, although it should actually be hidden since it is a html comment. For any reason, Redcarpet escapes the greater than < and less than > characters, thus rendering HTML comments unusable in markdown.

I do not want to use something like newlines <code>\n\n</code> as an excerpt_separator, because I want to be able to cut off an excerpt in the middle of a paragraph.

I am referring to the current Redcarpet version available at GitHub's Jekyll.

**Comment by fkostadinov** [comment]
Alright, I switched to using the excerpt separator &lt;span class="more">&lt;/span> in combination with the CSS rule <code>.more { display: none; }</code>. Not my top favorite solution but it works smoothly.

**Comment by StefanKrauth** [comment]
I had exactly the same issue and worked around it by changing the page and post layout to embed

{{ content | replace: '', '' }}

This cuts out the excerpt separator from the page and everything works as expected.

**Comment by eonist** [comment]
I cant get the {{ content | replace: '', '' }} trick to work, if I use another excerpt marker like end_exc it works. using a html comment feels better though. Ill keep looking.

**Comment by eonist** [comment]
Found a better solution: {{ content | remove_first: '&lt;!--more--&gt;', '' }}

Now you can use  as a global excerpt_separator in config.

You can use http://www.freeformatter.com/html-escape.html#ad-output to escape any word you want.

**Comment by zswyche** [comment]
Where exactly are you putting

    {{ content | remove_first: '', '' }}

is it supposed to replace {{ content}} like so?
```
  <div class="entry">
    {{ content | remove_first: '<!--more-->', '' }}
  </div>
```
This is still not working for me.  I guess I am putting the filter in the wrong place?

**Comment by eonist** [comment]
Here is where i put it: (post.html)
https://github.com/stylekit/stylekit.github.io/search?utf8=✓&q=remove_first

Here is my entire jekyll setup: https://github.com/stylekit/stylekit.github.io

Here is some context about this jekyll setup:
http://stylekit.org/blog/2016/01/06/The-Jekyll-Setup/

Good luck and cross your toes!

**Comment by Lrtwjhs** [comment]
Thank!
