### ISSUE TITLE
Empty headings

### ISSUE THREAD

**Issue by danschultzer** [vmg/redcarpet#425]
This is inconsistent:

```
2.1.1 :043 > parser.render "="
 => "<h1></h1>\n" 
2.1.1 :044 > parser.render "# "
 => "" 
```

Shouldn't it deliver the same result?

I'm parsing HTML to markdown, and back. Sometimes there is empty headings in the HTML. I'm using the atx style headings, and I would've guessed it to be a valid heading? Even multiple spaces gives nothing:

```
2.1.1 :048 > parser.render "#  "
 => "" 
```

Couldn't find any information on this in any documentation, so not sure if this is valid or not. Seems to be in javascript markdown parsers.

**Comment by dddanielpena** [comment]
test android

**Comment by robin850** [comment]
Hello,

Sorry for the very late answer but actually the two syntaxes for headers are different as the `=` syntax is beneath the header's text while the `#` syntax is ahead.

Also, the "plain old" Markdown specification isn't saying anything about empty atx headers so, to avoid any breaking change, let's not change this behavior.

You can always resort to a custom render object that would implement a `preprocess` method that would check for lines that start with any number of `#` but has no text and remove them.

Thanks for reporting anyway, I'm giving this a close.
