### ISSUE TITLE
no_intra_emphasis with @ symbol

### ISSUE THREAD

**Issue by DmytroVasin** [vmg/redcarpet#430]
```ruby
def render_with(flags, text)
  Redcarpet::Markdown.new(Redcarpet::Render::HTML, flags).render(text)
end

markdown = render_with({:no_intra_emphasis => true}, '@_dependencies of some_method')
```
will produce: 
`<p>@<em>dependencies of some</em>method</p>`

instead of simple:
`<p>@_dependencies of some_method</p>`

**Comment by robin850** [comment]
Hi there !

Sorry for the laaate answer ! Actually this is the expected behavior ; you can enable the `no_intra_emphasis` option instantiating the `Redcarpet::Markdown` object to match the desired behavior.

Thanks for reporting anyway ! :-)
