### ISSUE TITLE
redcarpet install error: exit code 2

### ISSUE THREAD

**Issue by mig-25** [vmg/redcarpet#432]
I am on a win8.1 machine with Ruby193 installed and the DevKit-tdm-32-4.5.2-20111229-1559-sfx.exe devkit installed.
I followed the steps described on the  [Development Kit](https://github.com/oneclick/rubyinstaller/wiki/Development-Kit) page.
This is the error message I got when running gem install redcarpet:

``` ruby
PS C:\> gem install redcarpet
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing redcarpet:
        ERROR: Failed to build gem native extension.

    C:/Ruby193/bin/ruby.exe -r ./siteconf20141106-2036-14rcfx6.rb extconf.rb
creating Makefile

make  clean
Makefile:165: *** target pattern contains no `%'.  Stop.

make
Makefile:165: *** target pattern contains no `%'.  Stop.

make failed, exit code 2

Gem files will remain installed in C:/Ruby193/lib/ruby/gems/1.9.1/gems/redcarpet-3.2.0 for inspection.
Results logged to C:/Ruby193/lib/ruby/gems/1.9.1/extensions/x86-mingw32/1.9.1/redcarpet-3.2.0/gem_make.out
```

Funny thing though, I got it running on my office laptop also with the same OS and the same ruby version.

I need redcarpet and the devkit to be installed  to able to run the Hologram gem.

**Comment by oookotooo** [comment]
also install ruby-dev, also it works only on ubuntu 16,04
it doesnt work on 14.04
