### ISSUE TITLE
`block_code` gets after `paragraph` in `Redcarpet::Render::HTML`

### ISSUE THREAD

**Issue by exalted** [vmg/redcarpet#444]
Hi,

`block_code` gets after `paragraph` in `Redcarpet::Render::HTML`, which is incoherent to how, for instance, `list` and `list_item` work.

When you override `list`, then you get the chance to internally call `list_item` passing it raw contents, whereas the same logic doesn't apply to `block_code` and `paragraph`.

This is biting me, because I am rendering custom markup for in `paragraph` that I would rather not have inside a `<blockquote>`, unfortunately that doesn't seem to be possibile right now.

```ruby
class CustomRenderer < Redcarpet::Render::HTML
  def paragraph(text)
    custom_paragraph(text)
  end

  def block_quote(quote)
    "<blockquote>#{standard_paragraph(quote)}</blockquote>"
  end

  private

  def standard_paragraph(text)
    "<p>#{text}</p>"
  end

  def custom_paragraph(text)
    "<p class=\"whatever\">#{text}</p>"
  end
end
```

Any ideas?

Thanks.

**Comment by robin850** [comment]
Hi @exalted !

Actually callbacks are working as expected ; most of the times, callbacks are overridden just to customize the tag that is used for a specific element (e.g. adding a class to a code block) ; the content of the tag should remain the same.

Moreover, the behavior that you want is really specific to your example ; having to override all other callbacks that rely on the one you are customizing would be problematic (e.g. having to rewrite `list` to make sure that it relies on your new definition of `list_item`). Also having such level of customization would be pretty hard to handle as we could imagine a specific handling of links inside block quotes for instance.

One possible solution (far from ideal, though) would be to remove the unwanted tags from the yielded content (with a tool like Oga or Nokogiri) and then wrap it with the ones that you want to use.

I'm giving it a close but thanks for spotting this!

**Comment by exalted** [comment]
👍
