### ISSUE TITLE
autolink renders URL params incorrectly (ampersands converted to entities)

### ISSUE THREAD

**Issue by debajit** [vmg/redcarpet#446]
### Steps to Repro

Render a URL with parameters e.g. 'http://a.com/?k1=v1&k2=v2'

**Expected output:**

```
"<p><a href=\"http://a.com/?k1=v1&k2=v2\">http://a.com/?k1=v1&amp;k2=v2</a></p>\n"
```

**Actual output:**

```
"<p><a href=\"http://a.com/?k1=v1&amp;k2=v2\">http://a.com/?k1=v1&amp;k2=v2</a></p>\n"
```

The link in the `<a href>` is broken.

---
### Details

```
html_renderer = Redcarpet::Render::HTML.new
url = 'http://a.com/?k1=v1&k2=v2'
```
#### Without autolink (Correct):

```
md = Redcarpet::Markdown.new(html_renderer)
md.render url 
# => "<p>http://a.com/?k1=v1&amp;k2=v2</p>\n"
```
#### With autolink (a href is incorrect):

```
md = Redcarpet::Markdown.new(html_renderer, autolink: true)
md.render url
# =>  "<p><a href=\"http://a.com/?k1=v1&amp;k2=v2\">http://a.com/?k1=v1&amp;k2=v2</a></p>\n"
```

**Comment by nolman** [comment]
Perhaps I am missing something but I believe this is actually a bug? ```http://localhost:3000/?foo=bar&amp;biz=baz``` will parse via rack as: ```{"foo"=>"bar", "amp;biz"=>"baz"}```

**Comment by mdeniz** [comment]
This is actually a bug. if you try something like this for instance `http://www.google.com/search?foo=1&amp;q=needle` it doesn't work. In other hand if you try this `http://www.google.com/search?foo=1&q=needle` it works.
Please reopen.

**Comment by robin850** [comment]
Hi there !

This is actually not a bug in my opinion ; historically, all HTML-entities are automatically escaped for security reasons -- Redcarpet is expected to generate HTML output that is safe to read for any user. Actually browsers automatically translate back escaped entities to their original char when clicking a link for instance.

I agree with you that processing URLs directly from the output Markdown can be problematic but you can always change this behavior through a custom render object:

~~~ruby
class CustomRender < Redcarpet::Render::HTML
  def autolink(link, link_type)
    return %(<a href="#{link}">#{link}</a>)
  end
end
~~~

**Comment by jrabramson** [comment]
Not sure why this was dismissed, still broken.

**Comment by robin850** [comment]
@jrabramson : This is fixed on the master branch ; we just need to push a release so you can benefit from this fix, I hope to do so soon.

**Comment by jrabramson** [comment]
FYI master branch is still entitying ampersands for me

**Comment by robin850** [comment]
@jrabramson : Could you give a reproduction script if it's the case please ?

~~~ruby
require 'redcarpet'

parser = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true)

puts parser.render <<-Md
Visit: http://a.com/?k1=v1&k2=v2
Md
~~~

outputs:

~~~html
<p>Visit: <a href="http://a.com/?k1=v1&k2=v2">http://a.com/?k1=v1&amp;k2=v2</a></p>
~~~

Maybe you are speaking about the escaped entities in the link's text but that's the expected behavior, we are just not entity-encoding the href.

**Comment by jrabramson** [comment]
I see, but if you don't use autolink and render a URL it will have the escaped entities. This is intentional?
