### ISSUE TITLE
Linebreaks inside html5 tags

### ISSUE THREAD

**Issue by soma** [vmg/redcarpet#450]
Hello. I am trying to port our usage of github-markdown to redcarpet and notice a difference in the parsing. I wonder if this is a bug or intentional, and if so if there is a workaround.

This script produces different outputs like below:

```ruby
str = "
<address>
Something address
Something 4C
2620 Blabla
</address>
"

p Redcarpet::Markdown.new(Redcarpet::Render::HTML.new(hard_wrap: true)).render(str).html_safe
p GitHub::Markdown.render_gfm(str).html_safe

=>

"<address>\nSomething address\nSomething 4C\n2620 Blabla\n</address>\n"
"<p><address><br>\nSomething address<br>\nSomething 4C<br>\n2620 Blabla<br>\n</address></p>\n"
```

I would like the linebreaks to be there.

**Comment by robin850** [comment]
Hi @soma,

Unfortunately as per the [Markdown specs](http://daringfireball.net/projects/markdown/syntax#html), we aren't doing any processing inside HTML blocks. You'll have to implement a custom render to handle this specific case:

~~~ruby
class CustomRender < Redcarpet::Render::HTML
  def block_html(raw_html)
    case raw_html
    when /<address>/
      raw_html.strip.gsub("\n", "<br>")
    else
      raw_html
    end
  end
end
~~~

I'm giving it a close, thanks for spotting this!
