### ISSUE TITLE
HTML_TOC fails when encountering '#' as comment start flag within code blocks

### ISSUE THREAD

**Issue by brxue** [vmg/redcarpet#451]
Hi,

I'm trying to use HTML_TOC as a render to generate TOC. 

Looks like it will regard the fake '#' as headers when it is within code blocks. for example, "make some nice lexed html" in the following code pieces will be rendered as header.

``` ruby
# make some nice lexed html
source = File.read('/etc/bashrc')
formatter = Rouge::Formatters::HTML.new(css_class: 'highlight')
lexer = Rouge::Lexers::Shell.new
formatter.format(lexer.lex(source))

# Get some CSS
Rouge::Themes::Base16.mode(:light).render(scope: '.highlight')
# Or use Theme#find with string input
Rouge::Theme.find('base16.light').render(scope: '.highlight')
```

**Comment by robin850** [comment]
Hi @brxue,

Actually this is something that may not seem obvious but when you're instantiating `Redcarpet::Markdown` with a `HTML_TOC` render object, you need to pass the `fenced_code_blocks` option as well. Unfortunately we can't really enable this by default as the render object and the `Markdown` one are kind of independent each other. I'm giving it a close but thanks for reporting anyway!

**Comment by brxue** [comment]
Thanks robin850! It solved my problem!

**Comment by born4new** [comment]
We encountered the same problem....Do you think it would be worth mentioning it in the README? I believe it could help other people...

**Comment by robin850** [comment]
@born4new : Actually the solution was fairly easy, we just need to enable the option by default passing a `HTML_TOC` object. This will be enabled by default in the next version of Redcarpet, thank you very much for the heads up ! 😀
