### ISSUE TITLE
Is there any way to add a class to a table?

### ISSUE THREAD

**Issue by tomjohnson1492** [vmg/redcarpet#453]
Is there any way to add a class to a table?

**Comment by robin850** [comment]
Hello @tomjohnson1492,

Yup, you need to implement a custom render object overriding the `table` callback like this:

~~~ruby
class CustomRender < Redcarpet::Render::HTML
  def table(header, body)
    "<table class=\"custom_class\">" \
      "#{header}#{body}" \
    "</table>"
  end
end
~~~

and then use it initializing the `Redcarpet::Markdown` object.

**Comment by tomjohnson1492** [comment]
Once I add this render object, is there a way to specify this particular class of table in the markdown syntax? Suppose I have 3 table styles and want to choose one table style for one page, another table style on another page, etc?

**Comment by Tuckie** [comment]
[If you're not hard set on using redcarpet...](http://kramdown.gettalong.org/syntax.html#block-ials)

**Comment by robin850** [comment]
@tomjohnson1492 : Nope that's not possible at the moment (and I don't know if this will be possible in the future ; cross-refs #306). Markdown doesn't aim at replacing HTML but I can understand the need for such feature.

**Comment by ekilah** [comment]
late post, but I found this solution useful & want to post an update for others. #413 shows a solution like this, but makes sure to use the `<thead>` tag:

```ruby
class CustomTableRender < Redcarpet::Render::HTML
  def table(header, body)
    "<table class='table'>" \
      "<thead>#{header}</thead>" \
      "<tbody>#{body}</tbody>" \
    "</table>"
  end
end
```

I reached the same solution on my own by browsing the C source of this gem, but apparently didn't need to :stuck_out_tongue: - hope this helps someone else!
