### ISSUE TITLE
Markdown inside of hyperlink markdown doesn't work.

### ISSUE THREAD

**Issue by VertigoRay** [vmg/redcarpet#456]
[Originally posted here](https://github.com/gitlabhq/gitlabhq/issues/8643) and was redirected to redcarpet.

# Description

When you use markdown inside of the markdown's square brackets to create bold, italics, etc ... it shows the html instead of generating the html. Shown in Example 1.

Additionally, when you use HTML inside of the markdown's square brackets to create bold, italics, etc ... it shows the no evidence of formatting changes. Shown in Example 2.

## Example 1

**Markdown:**

`the [fox *runs* fast](http://example.com).`

**Results:**

the [fox \<em\>runs\</em\> fast](http://example.com).

**Expected:**

the [fox *runs* fast](http://example.com).

## Example 2

**Markdown:**

`the [fox <em>runs</em> fast](http://example.com).`

**Results:**

the [fox runs fast](http://example.com).

**Expected:**

the [fox <em>runs</em> fast](http://example.com).

**Comment by robin850** [comment]
Hi @VertigoRay, it looks like this is not a Redcarpet issue (see https://github.com/gitlabhq/gitlabhq/issues/8643#issuecomment-71324617). I'm giving it a close but we can consider reopening if this is actually the case. Thanks!
