### ISSUE TITLE
new line issue

### ISSUE THREAD

**Issue by tomkadwill** [vmg/redcarpet#458]
There seems to be an issue with adding new lines. I've seen a previous fix #211. However, the issue seems to have reappeared in ruby 2.1.2

**Comment by robin850** [comment]
Hi @tomkadwill,

I'm not sure to understand what's the problem here ; do you mean that you see these failures again with Ruby 2.1.2 ?

**Comment by robin850** [comment]
Ok, I will give this a close! FWIW, the pull request you mentioned fixed failures with Nokogiri and our test suite doesn't use Nokogiri anymore. If it's another problem, feel free to comment and we can reopen. Thanks! :+1:
