### ISSUE TITLE
Image title attribute is always "# {title }"

### ISSUE THREAD

**Issue by benwalsh** [vmg/redcarpet#461]
`![Some image](/some_image.png)`
and
`![Some image](/some_image.png "With a title")`

both yield:

`<img src="/some_image.png" alt="Some image" title="# {title }">`

**Comment by robin850** [comment]
Hello @benwalsh,

It looks like you're using a custom render object that has a kind of syntax issue ; the default Redcarpet stack isn't using Ruby interpolation for rendering. I'm giving it a close but if I'm wrong, let us know and we can reopen.

**Comment by benwalsh** [comment]
Ah, looks like that's what it is. Thank you.
