### ISSUE TITLE
`html_escape` into wrong escape char in Render::Safe

### ISSUE THREAD

**Issue by david50407** [vmg/redcarpet#462]
https://github.com/vmg/redcarpet/blob/master/lib/redcarpet.rb#L57

```
 "/" => '&#x2F',
```

`"/"` must be translated into `'&#x2F;'` (with the missing `;`)

**Comment by robin850** [comment]
Hi @david50407,

Good catch! Thanks for reporting it and trying out the `Safe` render object! This has been fixed on master and this will be included in Redcarpet 3.2.3 (that should be released pretty soon I hope).
