### ISSUE TITLE
Autolink issue with brackets

### ISSUE THREAD

**Issue by ryanseys** [vmg/redcarpet#465]
`markdown.render("https://github.com/golang/go.")` produces 
```
"<p><a href=\"https://github.com/golang/go\">https://github.com/golang/go</a>.</p>\n"
```

which is correct, with the period outside of the link.

However `markdown.render("(https://github.com/golang/go.)")` produces:
```
"<p>(<a href=\"https://github.com/golang/go.\">https://github.com/golang/go.</a>)</p>\n"
```

with the period inside. This should probably not happen.

**Comment by robin850** [comment]
Hi @ryanseys  !

Sorry for the delay here ! This is now fixed, thanks for reporting ! :-)
