### ISSUE TITLE
Unexpectedly autolinks text inside parentheses separated by a space

### ISSUE THREAD

**Issue by vyp** [vmg/redcarpet#471]
_— Possible bug? —_

``` shell
$ ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
```

Installed Redcarpet with `gem install redcarpet`.

---

Hello, is this the parser that Github uses to render markdown files on the site? (As suggested by https://github.com/github/markup#markups) If not, can you point me to it?

Regardless, this might be a bug with redcarpet. Although I haven't found any previous issue that addresses this, I haven't gone through them all, so apologies if this is a duplicate.

---

Running:

``` ruby
#!/bin/env ruby

require 'redcarpet'

markdown = Redcarpet::Markdown.new(
  Redcarpet::Render::HTML,
  autolink: true
)

puts markdown.render(
  "[ref]" +

  "\n" +

  "[ref]: http://link.xyz"
)
```

results in expected output*:

``` html
<p><a href="http://link.xyz">ref</a></p>
```

But running:

``` ruby
#!/bin/env ruby

require 'redcarpet'

markdown = Redcarpet::Markdown.new(
  Redcarpet::Render::HTML,
  autolink: true
)

puts markdown.render(
  "[ref] (non-link text)" +

  "\n" +

  "[ref]: http://link.xyz"
)
```

results in:

``` html
<p><a href="non-link%20text">ref</a></p>
```

whereas expected output is:

``` html
<p><a href="http://link.xyz">ref</a> (non-link text)</p>
```

*Obviously without syntax highlighting (if you are reading on Github), which is just added here to help readability.

---

Is this expected? I can't find which specification of markdown redcarpet conforms to?

I don't think Gruber's original specification says anything about 'auto-references', i.e. when omitting the second pair of square brackets in link syntax. However, it does allow the second pair of _square_ brackets to be separated by a space (from http://daringfireball.net/projects/markdown/syntax#link):

```
This is [an example] [id] reference-style link.
```

For the record, the flavour of markdown I'm using produces the output (I) expected above.

**Comment by blackst0ne** [comment]
What's the status of this bug?

**Comment by deckar01** [comment]
This is related to https://github.com/vmg/redcarpet/issues/610.

Technically white space is allowed between the parts of a link. It's not surprising that `[text] (link)` syntax has a higher precedent than `[reference]` syntax. As far as makdown is concerned, that is a valid link href. Other markdown engines disable the options space between link parts to avoid these kinds of ambiguities. https://github.com/vmg/redcarpet/issues/610 proposes adding an option for this.

You will need to escape the open parenthesis for now:

```md
[test] \(junk)
[test]: hello
```

```html
<p><a href="hello">test</a> (junk)</p>

**Comment by robin850** [comment]
Hi there !

Sorry, I'm (a bit) late to the party but actually yes, this would be super hard to determine whether a reference is in the middle of a sentence which would be nuanced with some text between braces or whether it's actually a link.

Markown doesn't explicitly allows spaces between the link text and the reference but CommonMark explicitly [disallows it](http://spec.commonmark.org/0.27/#links):

> An inline link consists of a link text followed **immediately** by a left parenthesis.

Even though the original Markdown.pl allows the use of `[reference]` without extra brackets, it's not officially allowed in the spec. So you should rather always use `[reference][]`.

Thanks for reporting anyway and sorry for such "delay" ! ❤️

**Comment by vyp** [comment]
Hey, no worries.

CommonMark was still very much in it's infancy when I opened this issue. In fact, when I opened this issue, I think I used a reference implementation of it, or otherwise something else made by John (I don't remember exactly), when I said:

> For the record, the flavour of markdown I'm using produces the output (I) expected above.

I'm glad that github flavoured markdown is apparently a superset of commonmark now, and I have no problem agreeing with what the commonmark spec says, they know what they're doing.

That being said, Your quote about commonmark disallowing spaces in between the inline link text and it's destination is exactly the point with this issue. I wasn't trying to define an inline link with it's destination separated by a space, I was just trying to write a shortcut reference link, and then some normal text surrounded in parentheses, but redcarpet interpreted it as the former.. and that goes against the commonmark spec.

Also, commonmark the spec does officially and explicitly allow the use of `[reference]` without extra brackets. It's called a [shortcut reference link](http://spec.commonmark.org/0.27/#shortcut-reference-link).

The text below [example 510](http://spec.commonmark.org/0.27/#example-510) I think may clarify some points, particularly:

> (Note that shortcut reference links were introduced by Gruber himself in a beta version of Markdown.pl, but never included in the official syntax description. Without shortcut reference links, it is harmless to allow space between the link text and link label; but once shortcut references are introduced, it is too dangerous to allow this, as it frequently leads to unintended results.)

But note however that this is specifically only talking about *reference* style links, not inline links. Both Gruber's original markdown and commonmark still disallow whitespace in between link text and destination in inline links whether shortcut reference links are allowed or not. So talking about these shortcut reference links is sort of irrelevant anyway to this issue, as I understand.

The spec itself contains over 500 embedded example tests which you can [use](https://github.com/jgm/CommonMark#running-tests-against-the-spec) to see how well your implementation conforms to the spec. Cheers :sparkles:

**Comment by vyp** [comment]
@deckar01 So to clarify, #610 would go against [commonmark spec](http://spec.commonmark.org/0.27/#example-512):

> This is a departure from John Gruber’s original Markdown syntax description, which explicitly allows whitespace between the link text and the link label. It brings reference links in line with inline links, which (according to both original Markdown and this spec) cannot have whitespace after the link text. More importantly, it prevents inadvertent capture of consecutive shortcut reference links. If whitespace is allowed between the link text and the link label, then in the following we will have a single reference link, not two shortcut reference links, as intended:

(I'm not trying to argue or make a point, just trying to help with understanding and making things clearer. :+1:)

**Comment by deckar01** [comment]
@vyp The underlying issue reported in #610 is fixed in commonmark. I proposed adding a setting, but settings are apparently discouraged and this library doesn't have plans to comply with commonmark that I know of.

**Comment by vyp** [comment]
I thought that this parser was used by GitHub when I opened this issue, which is why I talked so much about commonmark in my last few comments, because apparently github flavoured markdown is now a superset of commonmark. Anyone know what GitHub uses for their github flavoured markdown parser? (If they've disclosed it.)

**Comment by robin850** [comment]
@vyp : Thanks for clarifying things !
Actually yes, GitHub uses a superset of CommonMark at the moment for their Markdown rendering.

@deckar01 : At the moment, to be totally honest, when there's an issue with rendering and the behavior isn't described in the original Markdown specs, I just look at the CommonMark ones so even though we are not complying with it at the moment, I hope it will be the case in the near feature (but still supporting things that CommonMark doesn't support likes tables etc. through options).
