### ISSUE TITLE
Header's tag is wrapped incorrectly under certain situations on windows platform

### ISSUE THREAD

**Issue by Alfred-Sun** [vmg/redcarpet#474]
### Environment

- ruby: **ruby 2.0.0p598** (2014-11-13) [i386-mingw32]
- redcarpet: 3.1.2 & **3.2.2**, others maybe
- pygments.rb: 0.6.1
- os: **windows** 7 & XP (it works well under Linux)

### Issues: missing headers' start tag or end tag

When rendering markdown text with "pygments" highlighter, sometimes start tag or end tag of the header would get lost and the output html is shown badly.

For example, look at this code ([**issue one**](https://gist.github.com/Alfred-Sun/6377b2c2692641349470)), missing the end tag of **h2**: 
`## 退出` => `<h2>退出<div class="highlight">...`.

And this one ([**issue two**](https://gist.github.com/Alfred-Sun/9e9325f67f66445c5f18)) losts start tag: 
`## 退出 ##` => `退出</h2><div class="highlight">`.

I encountered this problem when parse markdown file with Jeklly originally.

[**Test Code**](https://gist.github.com/Alfred-Sun/5e1f44bfdd19832f50fe) 
I have used above code to debug "Redcarpet::Markdown.new.render" function

### Guessing

At first, I thought it resulted from Jekyll or pygments.rb's highlighting function.
But when debugging, I found both generated the right highlighted code, and after redcarpet parsing, the header's tag got lost (I don't know how redcarpet parses markdown text).

By far, it occurred only if write markdown mixed with **Chinese text and English text**. To my surprised, it generates the good html when delete several characters in both files. And on Linux it won't do so.

Besides, if don't use highlighter, the generated header's tag is correct.

Do you know why ?

-------
_btw, it's a little difficult to reproduce the issue, but it always find me once I write a very long post mixed with two languages._

**Comment by wrwatson** [comment]
I have come across the same problem on Windows.  In my case, HTML was generated with no opening <h4> tag:

```html
Customer Credit Card</h4>
```

This particular part of the markdown is simply:

     #### Customer Credit Card

The problem seems to be caused by some earlier problem in the markdown, however I'm unable to locate the cause.

(I will attempt to narrow down a smaller test case).

**Comment by Lin-H** [comment]
I came across this problem too. Missing start tag or end tag. But when I used no extension of redcarpet       everything is fine ! I also notice that when I insert a space in `Vectors(向量)` between `s` and `(` the missing `</h2>` is back.
- os: windows 7
- redcarpet (3.2.3)

How weird.

**Comment by nitoyon** [comment]
I found a simple source code to reproduce this issue.
```ruby
require 'redcarpet'

class TestRenderer < Redcarpet::Render::HTML
  def emphasis(text)
    "a" * 117
  end
end

markdown = Redcarpet::Markdown.new(TestRenderer)

puts markdown.render("*a*\n# aaa")

# expected: <h1>a</h1>
# actual:   a</h1>
```

This problem is caused by failing `bufprintf`, because MinGW's `vsnprintf` doesn't support C99. I'll send PR to fix this bug:smile:

**Comment by robin850** [comment]
Thanks guys for reporting and @nitoyon for fixing it! :heart: :blue_heart: :yellow_heart: :green_heart: :purple_heart:
