### ISSUE TITLE
remove requirement of at least three dashes in separating line

### ISSUE THREAD

**Issue by garfieldnate** [vmg/redcarpet#476]
I wrote out a table with a small column like this:

xyz | a | bcde
---- | - | ----
x   | y | z

I was surprised to find that the table fails to render entirely unless I change the `| - |` to have at least three dashes (GitHub uses this library, so you won't see a table above unless this "feature" is changed). I'm not sure why the requirement is there, but it is [hardcoded].(https://github.com/vmg/redcarpet/blob/master/ext/redcarpet/markdown.c#L2337). 

Is there any way you can remove it? If not, it needs to be documented.

**Comment by mattr-** [comment]
We'll take a look at this issue. Thanks for reporting! 

Also, GFM isn't rendered using redcarpet anymore, so we don't have to worry about this issue affecting anything on GitHub, fortunately for us. :smiley:

**Comment by vyp** [comment]
@mattr- what is GFM rendered by? (And I'm assuming GFM means the markdown of the markdown files in repositories, i.e. README.md?)

**Comment by mattr-** [comment]
I believe it's done by jch/html-pipeline and other internal stuff now. I'm not sure because I don't work at GitHub.

**Comment by vyp** [comment]
Thanks for the info! I thought that if you know it isn't rendered by redcarpet, you might also know what it is rendered by.

**Comment by garfieldnate** [comment]
Actually the reason I reported this here was because I first reported the problem to GitHub, and they pointed me here. Perhaps it was a very recent change and they're not all caught up?

**Comment by vyp** [comment]
Ah that's strange. If you don't mind me asking, where did you report it to? Was it on a github repository, and if so, can I get a link? (I can't find anything at github/markup.)

Btw, sorry, I know this is OT, I don't have an answer to your question.

**Comment by garfieldnate** [comment]
I reported it to support@github.com.

**Comment by vyp** [comment]
No worries, thanks.

**Comment by robin850** [comment]
(cross-refs #418)

**Comment by garfieldnate** [comment]
The github rep came back again saying "oops, we don't use redcarpet anymore, but I'll add your issue". I'll still think it's an issue, whether or not GitHub uses it.

**Comment by robin850** [comment]
Hi there !

Sorry I've been so long to take a look at that but this should now work ; I don't know why this has been added historically, for now this works as you want but I will try to find edge cases to ensure that we are not breaking anything before putting this in any release.

Thank you everyone ! :-)

**Comment by garfieldnate** [comment]
Thanks!
