### ISSUE TITLE
Tab in code blocks is not preserved

### ISSUE THREAD

**Issue by ginzel** [vmg/redcarpet#480]
Please preserve tab in code blocks.

```
ruby --version
ruby 1.9.3p484 (2013-11-22) [x86_64-linux]
bin/redcarpet --version
Redcarpet 3.2.0

echo -e '```\na\tb\n```' |bin/redcarpet |hexdump -C
00000000  3c 70 3e 3c 63 6f 64 65  3e 0a 61 20 20 20 62 0a  |<p><code>.a   b.|
00000010  3c 2f 63 6f 64 65 3e 3c  2f 70 3e 0a              |</code></p>.|
```
Imho there is no reason for Redcarpet to change tabs to spaces or vice versa.

Where to change the default tabstops which are not 8 characters?

There are "holy wars" about tab vs. space but they are irrelevant in this case.
http://lea.verou.me/2012/01/why-tabs-are-clearly-superior/
http://nickgravgaard.com/elastic-tabstops/

**Comment by robin850** [comment]
Hello @ginzel,

actually this has already been asked and there's nothing we can really do here (c.f. https://github.com/vmg/redcarpet/issues/153#issuecomment-8575386). I'm giving it a close but thanks anyway!
