### ISSUE TITLE
Links in Code; Local wiki link in typewritter font in Redmine

### ISSUE THREAD

**Issue by ginzel** [vmg/redcarpet#481]
How to format link to local wiki page in [Redmine](http://www.redmine.org/issues/15520) to be in typewriter (code) font, please? Consider

```
[[`Wiki`]] or `[[Wiki]]` vs. *[[Wiki]]* and **[[Wiki]]**
```
Is / Would be there a way how to make (implicit/explicit) links in inline code or code blocks?
Implicit link example:
```
sub reorder {…} # see http://www.redmine.org/boards/2/topics/45051
```
For example if 4 backtics would be used?
Explicit links could be started with [deprecated](http://en.wikipedia.org/wiki/List_of_Unicode_characters#cite_note-1) unicode character Latin Small Letter N preceded by apostrophe (U+0149) or ZERO WIDTH SPACE (U+200B) or ZERO WIDTH NO-BREAK SPACE (BOM, U+FEFF).

**Comment by robin850** [comment]
> How to format link to local wiki page in Redmine to be in typewriter (code) font, please?

I'm not sure to understand what you want to do but this is certainly what you are looking for:

~~~markdown
[`Wiki page`](link_to_wiki_page.html)
~~~

> Is / Would be there a way how to make (implicit/explicit) links in inline code or code blocks?

Unfortunately not at the moment and the case seems a bit too specific for inclusion in Redcarpet. By default, all the HTML tags are escaped for security concerns. However, you can implement a custom render object to avoid escaping `a` tags like this for instance:

~~~ruby
require 'cgi'

class CustomRender < Redcarpet::Render::HTML
  def block_code(code, lang)
    code = CGI::escape_html(code)
    code = CGI::unescape_element(code, "a") if lang != "html"

    "<pre>" \
      "<code class=\"#{lang}\">#{code}</code>" \
    "</pre>"
  end
end
~~~

If I misunderstood your request, feel free to comment and we can reopen, thanks! :-)
