### ISSUE TITLE
Subscript formatting

### ISSUE THREAD

**Issue by meganero** [vmg/redcarpet#484]
Hello,
From #395. I think superscript and subscript are generally used in pair(c.f. http://en.wikipedia.org/wiki/Subscript_and_superscript). It could be something odd without one.
Please take this into consideration.

**Comment by robin850** [comment]
Hi @meganero,

> I think superscript and subscript are generally used in pair

Well, as mentioned in #395, in science, yes, subscripts are generally used in combination with superscripts. However, while subscripts are only really used in science, superscripts are more widely used to write dates or more generally cardinals (e.g. 3<sup>rd</sup>).

@mattr- : Do you have any thoughts on this feature ?

**Comment by robin850** [comment]
Okay, I will close this one! There is most-likely no other area apart from science where subscripts could be useful and it's still very straightforward to do:

~~~html
CO<sub>2</sub>
~~~

Thanks anyway!

**Comment by arcticleo** [comment]
+1 for adding H~2~O subscript support. 

So one can mix HTML and Markdown? Per the response for issue #13 that sounds like a no go, because of the purpose of Markdown.

**Comment by robin850** [comment]
@arcticleo : The problem described in issue #13 is that you can't put Markdown code inside an HTML element; for instance, `<div>**bold**</div>` will not work, but this is possible to use HTML elements inline since there's no Markdown inside, like: `**Water**: H<sub>2</sub>O`.
