### ISSUE TITLE
Image resizing

### ISSUE THREAD

**Issue by polsVoice** [vmg/redcarpet#487]
I was wondering if Redcarpet supports image resizing, as mentioned in the top comment in [this StackOverflow thread.](http://stackoverflow.com/questions/14675913/how-to-change-image-size-markdown) For example, to display an image at 300px wide x 450px high:

``
![](http://www.example.com/myImage.png =300x450)
``

Would this type of behavior be considered an extension or a renderer?

**Comment by robin850** [comment]
Hi @polsVoice,

Actually that's pretty easy to implement yourself with a custom render:

~~~ruby
class CustomRender < Redcarpet::Render::HTML
  def image(link, title, alt_text)
    if title =~ /=(\d+)x(\d+)/
      %(<img src="#{link}" width="#{$1}px" height="#{$2}px" alt="#{alt_text}>")
    else
      %(<img src="#{link}" title="#{title}" alt="#{alt_text}">)
    end
  end
end
~~~

With this custom render, you'll have, however, to surround the `=wxh` syntax with quotes. If you do not want to, you can do `link = link.split(" ")` and do the `=~`on `link[1]` and replace `link` with `link[0]`.

Thanks for spotting this! :-)

**Comment by GreenGremlin** [comment]
One note, the image sizes shouldn't have units.

``` ruby
class CustomRender < Redcarpet::Render::HTML
  def image(link, title, alt_text)
    if title =~ /=(\d+)x(\d+)/
      %(<img src="#{link}" width="#{$1}" height="#{$2}" alt="#{alt_text}>")
    else
      %(<img src="#{link}" title="#{title}" alt="#{alt_text}">)
    end
  end
end
```

**Comment by robin850** [comment]
Ah thanks @GreenGremlin !

**Comment by soundasleep** [comment]
I think this would be a great idea to add into the engine. I found the example code a little broken (it wasn't following link, just title), this worked really well for me:

    def image(link, title, alt_text)
      if link =~ /^(.+?)\s*=+(\d+)(?:px|)$/
        # e.g. ![alt](url.png =100px)
        # e.g. ![alt](url.png =100)
        %(<img src="#{$1}" style="max-width: #{$2}px" alt="#{alt_text}">)
      elsif link =~ /^(.+?)\s*=+(\d+)(?:px|)x(\d+)(?:px|)$/
        # e.g. ![alt](url.png =30x50)
        %(<img src="#{$1}" style="max-width: #{$2}px; max-height: #{$3}px;" alt="#{alt_text}">)
      else
        %(<img src="#{link}" title="#{title}" alt="#{alt_text}">)
      end
    end

If you'd like I can submit this as a PR, perhaps as a renderer option. I think it's pretty common.

**Comment by drum445** [comment]
None of the above seem to work correctly, this did the trick for me
```ruby
class CustomRender < Redcarpet::Render::HTML
  def image(link, title, alt_text)

    parts = link.split(" ")
    link = parts[0]

    if parts.size == 1
      # ![alt](url.png)
      %(<img src="#{link}" title="#{title}" alt="#{alt_text}">)
    else
      w, h = parts[1].gsub("=", "").gsub("px", "").split("x")
      if h
        # ![alt](url.png =500x200)
        %(<img src="#{link}" width="#{w}" height="#{h}" alt="#{alt_text}">)
      else
        # ![alt](url.png =500x)
        %(<img src="#{link}" width="#{w}" alt="#{alt_text}">)
      end
    end
  end
end
```

**Comment by kirqe** [comment]
What about resizing with `![](http://www.example.com/myImage.png){width=70%}`? How can I process the `{width=70%}` part?
<img width="125" alt="Screenshot 2023-04-20 at 12 57 28" src="https://user-images.githubusercontent.com/5272402/233331951-4ada1794-360c-404c-9522-4d646beb3d60.png">
