### ISSUE TITLE
your ruby docs are lacking the constructor params

### ISSUE THREAD

**Issue by pedrozath** [vmg/redcarpet#488]
I don't see the params here

![screen shot 2015-05-23 at 10 39 37](https://cloud.githubusercontent.com/assets/913275/7784321/1390a370-0138-11e5-9512-db945fae551d.png)

**Comment by robin850** [comment]
Hi @pedrozath,

Actually the documentation is not really good at the moment. The documentation of the objects defined at the C level is rather nonexistent. I will close this ticket and cross-ref #482 ; we will handle that here.Thanks for spotting this!  :-)
