### ISSUE TITLE
What features does the default parser support? Is there a documentation?

### ISSUE THREAD

**Issue by jmuheim** [vmg/redcarpet#489]
I'm using the default parser like this:

    Redcarpet::Markdown.new(Redcarpet::Render::HTML)

As it seems to convert also non-standard stuff like inline code using back ticks (which is not part of the standard http://daringfireball.net/projects/markdown/ manual), I wonder what features it supports, and whether there is some documentation that I can send the users of my web application to so they can read about how to write markdown?

**Comment by robin850** [comment]
Hi @jmuheim,

Actually Redcarpet mostly matches the features of `Markdown.pl` by default and what the "specs" describe.

> whether there is some documentation that I can send the users of my web application to so they can read about how to write markdown?

The page that you want is certainly the [syntax](http://daringfireball.net/projects/markdown/syntax) one, where the [inline code syntax](http://daringfireball.net/projects/markdown/syntax#code) is explained for instance. :-)

I'm giving it a close, thanks for spotting this!
