### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by gjtorikian** [vmg/redcarpet#493]
I was wondering if there could be a new release for the `id` fixes made in https://github.com/vmg/redcarpet/issues/385. We're hoping to bump and deploy this to GitHub Pages: https://github.com/github/pages-gem/pull/143

**Comment by robin850** [comment]
Hi @gjtorikian,

Redcarpet version 3.3.0 has been tagged, we just need to wait @vmg to push it to RubyGems. Thanks! :-)

**Comment by gjtorikian** [comment]
Thanks!

**Comment by vmg** [comment]
Pushed. Thank you @robin850!
