### ISSUE TITLE
Parsing bullet with indent with 2 spaces at least to follow commonmark

### ISSUE THREAD

**Issue by mizchi** [vmg/redcarpet#500]
Follow to http://spec.commonmark.org/0.17/#example-192

In redcarpet need 4 spaces to create indent block.

I know redcarpet exists before commonmark but majar diffrence from commonmark is this one. Can you add options to parse spaces in bullet?

Example

```
- a
  - b
```

and

```
- a
    - b
```

become same output

**Comment by dumblob** [comment]
+1

**Comment by robin850** [comment]
I will close this one and cross-refs #429 ; CommonMark support won't happen soon but most likely in the future! For now, as a turn-around, you can use the `:disable_indented_code_blocks` option. Thanks!
