### ISSUE TITLE
Anchor syntax issues?

### ISSUE THREAD

**Issue by sneakernets** [vmg/redcarpet#501]
I can't find a solution to this online, but I may have a syntax issue between Markdown parsers.

For example, if I have: 

```
### [Getting Started](#getting_started)

## [Getting Started](id:getting_started)
```

I expect this code output from Redcarpet:
```html
<h3><a href="#getting_started">Getting Started</a></h3>
```

```html
<h2><span id="getting_started">Getting Started</span></h2>
```

But instead I get this:
```html
<h3><a href="#getting_started">Getting Started</a></h3>

<h2><a href="id:getting_started">Getting Started</a></h2>
```

Is this correct behavior? Note that I have been using [Mou](http://25.io/mou/) for my previous markdown->HTML needs, and the guide in Mou says this is proper Markdown syntax:

![screen shot 2015-07-07 at 3 23 08 pm](https://cloud.githubusercontent.com/assets/5595293/8556348/1e95e8e6-24bc-11e5-822d-4f2380332de9.png)

I'm using the git master branch for this. Any help would be appreciated!

**Comment by robin850** [comment]
Hi @sneakernets!

Actually this is not standard Markdown so we do not support it by default ; this is a feature that is proposed by Mou. However you can implement a custom render object to bring such functionality to Redcarpet:

~~~ruby
class CustomRender < Redcarpet::Render::HTML
  def link(url, title, text)
    if url.start_with?("id:")
      %(<span id="#{url.split(":").last}">#{text}</span>)
    else
      %(<a href="#{url}" title="#{title}">#{text}</a>)
    end
  end
end
~~~

Thanks for spotting this!

**Comment by sneakernets** [comment]
Thanks for the code snippet!
