### ISSUE TITLE
Question: Wrap Headline and its Paragraph in p-Tag

### ISSUE THREAD

**Issue by phortx** [vmg/redcarpet#505]
Hi,

I need to wrap all headlines and their paragraphs in a `<p>`-Tag. Any idea how to implement that?

Example:

```md
# 1. Headline Level 1

This is some Text

## 1.1 Headline Level 2

This is even more Text

# 2. Another Headline Level 1

And this is text too
```

Should be parsed to:

```html
<p>
  <h1>1. Headline Level 1</h1>

  This is some Text

  <p>
    <h2>1.1 Headline Level 2</h2>

    This is even more Text
  <p>
</p>

<p>
  <h2>2. Another Headline Level 1</h1>

  And this is text too
</p>
```

Thank you for any advice in advance

**Comment by robin850** [comment]
H @phortx!

I'm sorry but this is not easily achievable at the moment and I don't know of a tool that would easily allow you to do that. At least [CommonMark](http://spec.commonmark.org/dingus/?text=%3Cp%3E%0A%0A%23%201.%20Headline%20Level%201%0A%0AThis%20is%20some%20Text%0A%0A%3Cp%3E%0A%0A%23%23%201.1%20Headline%20Level%202%0A%0AThis%20is%20even%20more%20Text%0A%0A%3C%2Fp%3E%0A%0A%3C%2Fp%3E%0A%0A%3Cp%3E%0A%0A%23%202.%20Another%20Headline%20Level%201%0A%0AAnd%20this%20is%20text%20too%0A%0A%3C%2Fp%3E) allows you to write Markdown inside HTML tags but I doubt Markdown is the Markup to use for your particular case, it is not intended to be a replacement for HTML. Also I'm pretty sure that this is not a valid HTML code. Thanks for spotting this anyway!
