### ISSUE TITLE
inline link in heading render bad

### ISSUE THREAD

**Issue by seaify** [vmg/redcarpet#510]
@mojombo @rtomayko @lsegal 
```html
### [rails_panel](https://github.com/dejan/rails_panel)
```
convert to html

```
<h3 id=\"&lt;a href=\" target=\"_blank\" https:=\"\">rails_panel\"&gt;<a href=\"https://github.com/dejan/rails_panel\" target=\"_blank\">rails_panel</a>\n</h3>
```

**Comment by robin850** [comment]
Hi @seaify!

Which version of Redcarpet are you using and with which options please ? I'm not able to reproduce this with 3.3.2:

~~~ruby
require 'redcarpet'

render = Redcarpet::Render::HTML.new(with_toc_data: true)
parser = Redcarpet::Markdown.new(render)

markdown = "### [rails_panel](https://github.com/dejan/rails_panel)"
puts parser.render(markdown)
~~~

which outputs:

~~~html
<h3 id="rails_panel"><a href="https://github.com/dejan/rails_panel">rails_panel</a></h3>
~~~

Also please avoid pinging people that are not involved in this project ; they are certainly busy enough. Thanks!

**Comment by seaify** [comment]
@robin850 
finally found out, it's ruby-china's bug, not redcarpet. https://github.com/ruby-china/ruby-china/pull/427.
```ruby
 class HTMLwithTopic < HTMLwithSyntaxHighlight
      def header(text, header_level)
        l = header_level <= 2 ? 2 : header_level
        %(<h#{l} id="#{text}">#{text}</h#{l}>)
      end
    end
```

Sorry for pinging them, after create issues and input @, thoes people appear, i thought they also maintain this project.

Thanks for your help!

**Comment by robin850** [comment]
No problem, thank you for the quick answer! :-)
