### ISSUE TITLE
prettify cannot add line number.

### ISSUE THREAD

**Issue by RathanakSreang** [vmg/redcarpet#511]
Hi I try to use redcarpet to markdown my code. But I cannot find option for add line number to my code. can you guy tell me how? thx

**Comment by robin850** [comment]
Hi @RathanakSreang,

You can implement a custom render object to provide such feature:

~~~ruby
class CustomRender < Redcarpet::Render::HTML
  def block_code(code, lang)
    if lang.include?("?")
      lang.gsub!("?", " ")
      lang.gsub!("l", "linenums")
    end

    output = "<pre>"
    output << "<code class=\"prettyprint lang-#{lang}\">#{code}</code>"
    output << "</code></pre>"
  end
end
~~~

Then you can either use `ruby?l` to enable line numbers or `ruby?l:8` to start line numbers at line 8. Also make sure to HTML-escape the given `code` variable if this render object is going to process users' input.

Thanks for spotting this!
