### ISSUE TITLE
some tests are failing with ruby 2.2

### ISSUE THREAD

**Issue by pravi** [vmg/redcarpet#513]
Can someone help fix those?
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=797101

**Comment by robin850** [comment]
Hello @pravi,

Thanks for reporting! This seems really weird ; the CI server doesn't fail on these tests and I'm not able to reproduce it locally. Could you give the necessary steps to reproduce this on a fresh Debian install please ?

Also, if you run the tests through `rake test` from the gem's directory, do you see such failures ?

**Comment by balasankarc** [comment]
Related to #497

**Comment by robin850** [comment]
Okay, it looks like it's your "setup" that is at fault rather than Redcarpet ; feel free to ask if I can be of any help with this issue! Thanks! :-)
