### ISSUE TITLE
Ruby crashing

### ISSUE THREAD

**Issue by itay-grudev** [vmg/redcarpet#514]
I've found a serious issue, causing the ruby interpreter to crash. There might be a problem with the native extensions you are building.

**Comment by itay-grudev** [comment]
Ok. I tracked it down. Take a look at the code I provided.

The `highlight: true` option doesn't work with the `Redcarpet::Render::StripDown`.

Even though this option is incorrectly used with this renderer, the fact that ruby crashes is an issue.

**Comment by itay-grudev** [comment]
Forget about the repo...
This excerpt causes ruby to crash:

```ruby
#!/usr/bin/env ruby

require 'redcarpet'
require 'redcarpet/render_strip'

markdown = Redcarpet::Markdown.new(
  Redcarpet::Render::StripDown.new,
  highlight: true
)

puts markdown.render("==Hello world==")

puts 'THIS LINE IS NEVER REACHED'
```

**Comment by itay-grudev** [comment]
I was missing a coma at the end of `:highlight`, so I overwrote the commit.

This could theoretically be a valid fix, not temporary, assuming nothing else will explode if it lacks the `highlight` method.

**Comment by robin850** [comment]
Thanks you very much for reporting and fixing this! :-)
