### ISSUE TITLE
tables not rendered despite option

### ISSUE THREAD

**Issue by joelmeyerhamme** [vmg/redcarpet#517]
With ruby-2.2.3 and redcarpet 3.3.2 tables aren't rendered despite having turned on the option. What am I doing wrong? 

```ruby
Redcarpet::Markdown.new(Redcarpet::Render::HTML, tables: true).render("| --- | ---|\n| ex | ample |")
=> "<p>| --- | ---|\n| ex | ample |</p>\n"
```

**Comment by joelmeyerhamme** [comment]
Sorry for the bother, I was not considering my own stupidity as much as I should have.

```ruby
"| | |\n| --- | ---|\n| ex | ample |"
```

**Comment by robin850** [comment]
Hi @joelmeyerhamme!

Yes, the table syntax may be improved at some levels (e.g. #411 and #476) ; I'm giving it a close but things may get easier with tables in the future! Thanks for reporting anyway!
