### ISSUE TITLE
Push 3.3.3 to Rubygems

### ISSUE THREAD

**Issue by shaneog** [vmg/redcarpet#518]
It looks like the latest release was not pushed to Rubygems.

**Comment by khelal** [comment]
+1

**Comment by seanhandley** [comment]
:+1:

**Comment by seanhandley** [comment]
Ended up here via http://www.be9.io/2015/09/21/memory-leak/

**Comment by khelal** [comment]
Can we help push this to rubygems?

**Comment by robin850** [comment]
We are waiting @vmg to push it to RubyGems ; I do not have the right to push it, sorry guys!

**Comment by vmg** [comment]
Pushed! Sorry for the delay.

**Comment by robin850** [comment]
Thank you! :-)
