### ISSUE TITLE
Pre tags on code are not added when you write code

### ISSUE THREAD

**Issue by jamesaduke** [vmg/redcarpet#521]
it does not add pre tags on code when it is written on article just provides breaks

**Comment by robin850** [comment]
@jamesaduke : I guess you are either using a custom render object or you don't have enabled the `fenced_code_blocks` option instantiating `Redcarpet::Markdown` ; both indented and fenced code blocks generate a `<pre>` tag.

I'm giving it a close but feel free to ask to reopen if I misunderstood something, thanks!
