### ISSUE TITLE
Unable to compile native extensions in OS X "El Capitan"

### ISSUE THREAD

**Issue by mstahl** [vmg/redcarpet#523]
Hi! I got the following output when I tried to `gem install redcarpet -v '3.3.3'` on my macbook running OS X 10.11.

```
/usr/local/opt/rbenv/versions/2.1.5/bin/ruby extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling autolink.c
compiling buffer.c
buffer.c:110:45: warning: passing 'const struct buf *' to parameter of type 'struct buf *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        if (buf->size + 1 <= buf->asize || bufgrow(buf, buf->size + 1) == BUF_OK) {
                                                   ^~~
buffer.c:59:21: note: passing argument to parameter 'buf' here
bufgrow(struct buf *buf, size_t neosz)
                    ^
1 warning generated.
compiling houdini_href_e.c
compiling houdini_html_e.c
compiling html.c
compiling html_smartypants.c
compiling markdown.c
markdown.c:2838:43: warning: passing 'const uint8_t *' (aka 'const unsigned char *') to parameter of type 'uint8_t *' (aka 'unsigned char *') discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
                if (codefences_enabled && (is_codefence(document + beg, doc_size - beg, NULL) != 0))
                                                        ^~~~~~~~~~~~~~
markdown.c:1391:23: note: passing argument to parameter 'data' here
is_codefence(uint8_t *data, size_t size, struct buf *syntax)
                      ^
1 warning generated.
compiling rc_markdown.c
compiling rc_render.c
compiling stack.c
linking shared-object redcarpet.bundle
ld: library not found for -lgmp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [redcarpet.bundle] Error 1

make failed, exit code 2
```

In particular, the line `ld: library not found for -lgmp` seemed odd to me. I didn't think that GMP was a dependency, so I poked around in the `ext/` directory and discovered that extconf added `-lgmp` to my cflags for some reason even though it's not mentioned in `extconf.rb` or anywhere.... Now that I've written this much, is this maybe an extconf bug? Not sure. I've already written this much already so....

**Comment by im-kulikov** [comment]
try this https://github.com/Homebrew/homebrew/issues/20041#issuecomment-18395843

Try `brew uninstall gmp; brew install gmp` and/or `brew unlink gmp; brew link gmp`.

**Comment by mstahl** [comment]
That worked. Thanks!

**Comment by im-kulikov** [comment]
well, fine 👍🏻

**Comment by robin850** [comment]
Hi!

Do you guys have this problem with installing 3.3.2 without gmp please ? This seems pretty strange that this problem is only spotted now!

**Comment by pex** [comment]
I ran into this same issue using
* OS X 10.11.1
* Ruby 2.2.3p173 (installed via Rbenv)
* gmp-6.0.0a (installed via Homebrew)

Reinstalling `gmp` did not help.

**Comment by pex** [comment]
@robin850 I tried installing 3.3.2 as well and got the same error (if that was your question)

**Comment by pex** [comment]
Just read https://github.com/Homebrew/homebrew/issues/13197 and reinstalled Ruby.
Worked for me.

**Comment by robin850** [comment]
Okay, I don't think this problem is related to Redcarpet ; this is certainly a larger problem with C extensions in general. I honestly don't know GMP at all but it is a required dependency for Ruby on my computer (running Arch Linux) so I think it's involved during the compilation process of native extensions.

Feel free to ask to reopen if I'm wrong, thanks for reporting everyone! :-)

**Comment by mstahl** [comment]
Yeah I was suspicious about it actually because it's hard for me to believe that GMP is a dependency of Redcarpet. I'm not sure why you'd need arbitrary-precision math to parse markdown files. Was posting here thinking it might be something else. Thanks for responding so quickly!
