### ISSUE TITLE
Multiline tables

### ISSUE THREAD

**Issue by Stemby** [vmg/redcarpet#525]
Could you implement something similar to [Pandoc multiline tables](http://pandoc.org/README.html#tables), please?

Thank you!

**Comment by robin850** [comment]
Hi @Stemby,

I will give this a close for the same reasons than #394 ; the table parsing is already complex enough and should fulfill a lot of common cases. The handle of tables is pretty "controversial" ; some people want it to handle complex cases while other people want it for very simple ones.

Thanks for the proposal anyway! :-)
