### ISSUE TITLE
Definition lists

### ISSUE THREAD

**Issue by Stemby** [vmg/redcarpet#526]
Could you implement definition lists, please?

Here is some examples taken from other markdown dialects:
* [Markdown Extra](https://michelf.ca/projects/php-markdown/extra/#def-list)
* [Kramdown and Maruku](http://kramdown.gettalong.org/syntax.html#definition-lists)
* [MultiMarkdown](https://github.com/fletcher/MultiMarkdown/wiki/MultiMarkdown-Syntax-Guide#definition-lists)
* [Pandoc](http://pandoc.org/demo/example9/pandocs-markdown.html#definition-lists)
* [Python Markdown](http://pythonhosted.org/Markdown/extensions/definition_lists.html)
* [Lunamark](http://jgm.github.io/lunamark/lunamark.1.html)

Thank you!

**Comment by robin850** [comment]
Hi @Stemby, I'm giving it a close because we can continue the discussion in #108 but thanks for the proposal! :-)
