### ISSUE TITLE
Unicode headers produce invalid anchors

### ISSUE THREAD

**Issue by mitchelltd** [vmg/redcarpet#527]
When redcarpet processes Unicode headers to produce anchors (for use in TOC generation) it returns invalid anchors. The anchor claims to be in UTF-8, but it contains hexadecimal codes. 

Worse, the hexadecimal codes are not valid. For example, it returns `\xE3\xA9` instead of `\xC3\xA9` for an é. I suspect that what is happening is that the string has been incorrectly converted to lowercase, changing \xc3 to \xe3. The lowercase conversion has assumed latin1 encoding when it was actually utf-8. (HT : [Janne Karila](http://stackoverflow.com/questions/14852224/unicode-latin1-string-encode-decode)

Example : 

`irb(main):001:0> require 'redcarpet'`
`=> true`
`irb(main):002:0> markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML_TOC)`
`=> #<Redcarpet::Markdown:0x007ff1eb831dc0 @renderer=#<Redcarpet::Render::HTML_TOC:0x007ff1eb831de8>>`
`irb(main):003:0> test = "# Précis"`
`=> "# Précis"`
`irb(main):004:0> rc = markdown.render(test)`
`=> "<ul>\n<li>\n<a href=\"#pr\xE3\xA9cis\">Précis</a>\n</li>\n</ul>\n"`
`irb(main):005:0> test.encoding`
`=> #<Encoding:UTF-8>`
`irb(main):006:0> rc.encoding`
`=> #<Encoding:UTF-8>`
`irb(main):007:0> puts "pr\xC3\xA9cis"`
`précis`
`=> nil`

**Comment by philoghn** [comment]
![888](https://cloud.githubusercontent.com/assets/15262849/11270137/ecc66546-8eee-11e5-87e1-3917ad68f371.jpg)

**Comment by philoghn** [comment]
https://enterprise.github.com/philoghn

**Comment by clemensg** [comment]
Hi @mitchelltd,

had the same problem today and I sent a pull request with a fix: #528 

It was the `tolower` function which is not locale-aware.

Please tell me if my fix works for you too.

**Comment by robin850** [comment]
Thank you for reporting and fixing it guys! :-)

**Comment by mitchelltd** [comment]
Sorry for the delay in replying. This doesn't fix it for me. Nothing has changed in my test example above.

I'm running Mac OS X 10.11.1

**Comment by clemensg** [comment]
Hi @mitchelltd,

that's odd, are you sure you are using the latest master version of redcarpet?

When I try your test with irb and the current master branch of redcarpet, I get:
```
2.2.3 :001 > require 'redcarpet'
 => true
2.2.3 :002 > markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML_TOC)
 => #<Redcarpet::Markdown:0x007f7fe940cfc0 @renderer=#<Redcarpet::Render::HTML_TOC:0x007f7fe940cfe8>>
2.2.3 :003 > test = "# Précis"
 => "# Précis"
2.2.3 :004 > rc = markdown.render(test)
 => "<ul>\n<li>\n<a href=\"#pr-cis\">Précis</a>\n</li>\n</ul>\n"
2.2.3 :005 > test.encoding
 => #<Encoding:UTF-8>
2.2.3 :006 > rc.encoding
 => #<Encoding:UTF-8>
2.2.3 :007 > puts "pr\xC3\xA9cis"
précis
 => nil
```

Now, the anchor is replaced with a dash.

First, I thought about adding a locale-aware tolower function but this would mean pulling in some iconv or ICU library. (There are so many edge cases, you do not want to code something like this yourself)
So, for my use case it was enough to just replace those non-ASCII characters with `-`.
Do you need it to be locale-aware lowercase?

**Comment by mitchelltd** [comment]
Hello @clemensg,

Many thanks ! You are absolutely right. I wasn't using the latest master version. I *had* checked that I was using the latest master version, but what I was checking was that `html.c` had changed. But that is insufficient. So I reinstalled with
`gem specific_install https://github.com/vmg/redcarpet master`

Re locale-aware lowercase. Obviously it would be better to have a locale-aware tolower function. As it is, the code is producing html which is not readable by humans. And in a Markdown context, you obviously want to preserve human-readability as far as possible. Having said that, having anchors that aren't human-readable doesn't actually break anything and should still work. 

Thanks again !

**Comment by robin850** [comment]
Yes I hope we will be more locale-aware in the future but thanks guys ! :-)

**Comment by philoghn** [comment]
Toi chinh sua van de facebook, khi toi lam khac di y ban dau thi khong chap nhan, vi vay toi phai theo dang ky sua lan dau ngay hom nay.Ben nay; ten cua toi; Dao Quang Ngoc, toi muon sua van de dau tien cho khop la; khong co chu VN ghep vao ten chinh cua minh.Cac ban biet hai ten cua toi tai day giong nhau dung khong, va url cua toi chuan dung khong?

**Comment by philoghn** [comment]
Toi noi lai mot lan cuoi cung; ai giup toi, toi ghi nhan va se tra on nguoi do,ban than toi khong doc ac tham lam nhu ban nghi, chi can ai noi toi hay nghi toi nhu tren hay nghi den ban than minh truoc tien roi noi toi nghe.Toi co the co nhieu san pham trung bay do suu tam va san xuat no ra boi vi nghe cua toi la Marketting, toi khong co tai nhung viec nay toi lai duoc be tren ban cho, chi tiec khong tai khong biet su dung.Moi khi suu tam nhieu qua muc cua phone, toi xoa di hang loat...Cong viec chinh cua toi tren duong, khong biet lai xe nhung nghe tieng no biet duoc xe tot hay kem, nhin va nghe khach hang biet duoc thuoc tang lop nao,den hom nay toi biet cong viec cua toi thanh cong hay that bai vi viec gi.Cam on cac ban thoi gian qua, hien tai toi co viec khong nhan duoc Email va su giup do cua doi Gihut nay mong cac ban thong cam.Toi biet minh phai lam gi, xoa gi va de lai nhung gi cho minh.
