### ISSUE TITLE
Rendering of markdown in HTML tags

### ISSUE THREAD

**Issue by fusion809** [vmg/redcarpet#532]
Hi,

I have asked a question at [StackOverflow](http://stackoverflow.com/questions/34192740/how-to-insert-markdown-within-html-tags-such-that-both-are-rendered-properly) that I suspect may be a bug (or lack of features) in this Markdown parser. 

Thanks for your time,
Brenton

**Comment by robin850** [comment]
Hi @fusion809,

This is actually not possible at the moment (see #13) ; we may support this feature in the future if we follow the [CommonMark specs](http://spec.commonmark.org/0.22/#html-blocks) that basically allow you to put Markdown between HTML tags if there is an empty lines between the markup and the tags.

I'm giving it a close but thanks for proposing this feature anyway!
