### ISSUE TITLE
Link to attachement with space in file name

### ISSUE THREAD

**Issue by ginzel** [vmg/redcarpet#533]
Please, consider non-alphanumeric chars in file names. E.g. `![alt](Attachment with spaces.png)`.

http://www.redmine.org/issues/18787

**Comment by robin850** [comment]
Hi @ginzel,

Sorry for the late answer, I guess this is useless after such a long time but for future references, this cannot work as the space char is used to separate the image's URL from its eventual title. You should rather rely on `%20`.

CommonMark also states that URLs should not contains spaces (the same rules are applied to links and images):

> A link destination consists of [...] a nonempty sequence of characters that does **not include ASCII space** or control characters [...].

Thanks for spotting this anyway ! :-)

**Comment by ginzel** [comment]
Thank you, @robin850 .
