### ISSUE TITLE
colspan or rowspan in td tag can't work when I using HTML table tag

### ISSUE THREAD

**Issue by wenweih** [vmg/redcarpet#534]
etc,I write the follow,but rowspan can't work

```
<table>
  <tr>
    <th>Month</th>
    <th>Savings</th>
    <th>Savings for holiday!</th>
  </tr>
  <tr>
    <td>January</td>
    <td>$100</td>
    <td rowspan="2">$50</td>
  </tr>
  <tr>
    <td>February</td>
    <td>$80</td>
  </tr>
</table>
```

I guess that I can override Redcarpet::Render::HTML `raw_html`method,but I don't konw how to do.
who can help me,thx 
@robin850

**Comment by robin850** [comment]
Hi @wenweih,

Sorry for the late answer here ! Could you describe the problem a bit more please ? I'm not sure to understand which issue you are facing.

**Comment by robin850** [comment]
Okay, I'm giving this a close since there's a lack of context here but feel free to comment if this is still a problem for you ! :-)
