### ISSUE TITLE
Header's tag attribute not close for chinese text

### ISSUE THREAD

**Issue by CatTail** [vmg/redcarpet#535]
Environment

* system: Mac OS 10.11.1
* redcarpet: 3.3.4

With a header all of chinese character

```
## 你好
```

generated html will be

```html
<h2 id=">你好</h2>
```

Note that id attribute is not complete

It seemed to related with #527

**Comment by rainzhaojy** [comment]
is it resolved? I met the same issue.

**Comment by robin850** [comment]
I'm giving this a close as #538 has a "richer" discussion but thank you very much for reporting !
