### ISSUE TITLE
Footnotes markup does not pass HTML5 validation

### ISSUE THREAD

**Issue by louh** [vmg/redcarpet#536]
The footnotes markup, as generated from [html.c](https://github.com/vmg/redcarpet/blob/45fe496316a586deffa48d2c8dd00c042c686093/ext/redcarpet/html.c#L641-L652), will not pass HTML5 validation because of the following reasons:
- The `rev` attribute is obsolete. (Sources: [HTML Living Standard](https://html.spec.whatwg.org/multipage/obsolete.html#attr-a-rev), [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-rev), [Microformats](http://microformats.org/wiki/rel-faq#Should_rev_even_be_used))
- The `rel` attribute no longer accepts `footnote` as a valid value, as it has been dropped in HTML5. (Source: [Microformats](http://microformats.org/wiki/existing-rel-values#dropped))

Take this sample output from Redcarpet:

``` html
<!DOCTYPE html>
<html>
<head>
  <meta charset='utf-8'>
  <title>Redcarpet footnotes markup example.</title>
</head>
<body>

<p>Reference 1<sup id="fnref1"><a href="#fn1" rel="footnote">1</a></sup></p>

<p>Reference 2<sup id="fnref2"><a href="#fn2" rel="footnote">2</a></sup></p>

<div class="footnotes">
<hr>
<ol>

<li id="fn1">
<p>Footnote 1&nbsp;<a href="#fnref1" rev="footnote">&#8617;</a></p>
</li>

<li id="fn2">
<p>Footnote 2&nbsp;<a href="#fnref2" rev="footnote">&#8617;</a></p>
</li>

</ol>
</div>

</body>
</html>
```

When I run it through the [(X)HTML5 Nu Validator service](https://html5.validator.nu/), I get the following errors:

```
    Error: Bad value footnote for attribute rel on element a: The string footnote is not a registered keyword.

    From line 9, column 32; to line 9, column 61

    ="fnref1"><a href="#fn1" rel="footnote">1</a><

    Syntax of list of link-type keywords:
        A whitespace-separated list of link types, with no duplicate keywords in the list. Each link type must be listed as allowed on <a> and <area> in the HTML specification, or must be listed as allowed on <a> and <area> on the Microformats wiki, or must be an absolute URL. You can register link types on the Microformats wiki yourself. 

    Error: Bad value footnote for attribute rel on element a: The string footnote is not a registered keyword.

    From line 11, column 32; to line 11, column 61

    ="fnref2"><a href="#fn2" rel="footnote">2</a><

    Syntax of list of link-type keywords:
        A whitespace-separated list of link types, with no duplicate keywords in the list. Each link type must be listed as allowed on <a> and <area> in the HTML specification, or must be listed as allowed on <a> and <area> on the Microformats wiki, or must be an absolute URL. You can register link types on the Microformats wiki yourself. 

    Error: The rev attribute on the a element is obsolete. Use the rel attribute instead, with a term having the opposite meaning.

    From line 18, column 20; to line 18, column 52

    te 1&nbsp;<a href="#fnref1" rev="footnote">&#8617

    Error: The rev attribute on the a element is obsolete. Use the rel attribute instead, with a term having the opposite meaning.

    From line 22, column 20; to line 22, column 52

    te 2&nbsp;<a href="#fnref2" rev="footnote">&#8617
```

The [W3C Recommendation for Footnotes](http://www.w3.org/TR/html5/common-idioms.html#footnotes) is simply to have the anchor links, without any `rel` attribute.

I understand that removing this might possibly break functionality for people who are using the `rel` and `rev` attributes for CSS selectors, so I wanted to raise this for discussion. Perhaps using class names (as with the `<div class='footnotes'>` already generated in Redcarpet output), is more appropriate.

**Comment by natelandau** [comment]
Is there an easy way to override this behavior on a one-off basis to allow validation support before some fix is adopted in the project as a whole?  Google just released their AMP pages which will not validate the 'rev' attribute on links.

**Comment by elomatreb** [comment]
This is fixable by overriding the `footnote_def` method in a custom renderer class.

```ruby
class CustomHTML < Redcarpet::Render::HTML
  def footnote_ref(number)
    "<sup class='footnote-ref'><a href='#fn#{number}'>#{number}</a></sup>"
  end
end
```

I would also like to say that I'd like to see this fixed. I don't think it should be necessary to create a custom renderer to get valid HTML.

**Comment by larryhynes** [comment]
I just ran into this, getting failed validation due to rel=footnote. This issue doesn't seem to have been addressed in any commits, so I'm wondering is there a plan to remove rel=footnote, or what's the advised 'way forward'?

**Comment by robin850** [comment]
Hi everyone,

Sorry it's been so long to address such a small issue but this is now solved and will be available in the next version of Redcarpet.

Thank you very much ! :heart:
