### ISSUE TITLE
List doesn't render unless blank line comes before the first list item

### ISSUE THREAD

**Issue by mhelmetag** [vmg/redcarpet#546]
It seems like lists are only render when theres a newline that interrupts a paragraph.

Currently the way to render a list is:
```
test

* test
- test
```

But it should also include (http://spec.commonmark.org/0.24/#example-259):
```
test
* test
- test
```

Here's some irb showing this:
```
[17] pry(main)> markdown = Redcarpet::Markdown.new(Redcarpet::Render::XHTML, options)
=> #<Redcarpet::Markdown:0x007fd464e1b2a8 @renderer=#<Redcarpet::Render::XHTML:0x007fd464e1b370>>
[18] pry(main)> content1 = "test\n\n* test"
=> "test\n\n* test"
[19] pry(main)> content2 = "test\n* test"
=> "test\n* test"
[20] pry(main)> markdown.render(content1)
=> "<p>test</p>\n\n<ul>\n<li>test</li>\n</ul>\n"
[21] pry(main)> markdown.render(content2)
=> "<p>test\n* test</p>\n"
```

I came up with a workaround in an app that uses redcarpet. Just uses a preprocess to add another newline before a list:
```
def preprocess(text_content)
  text_content.gsub(/^\w+\n(?=[*|-]\s\w+)/, "\\0\n")
end
```

I'm wonder... is this is expected? Totally low priority and just a nitpick. Just curious.

Thanks!

**Comment by skuridin** [comment]
Anybody?

**Comment by skuridin** [comment]
Ok, `lax_spacing: true` option helps

**Comment by mhelmetag** [comment]
@skuridin , thanks! That worked for me too.
