### ISSUE TITLE
Fenced code blocks do not allow empty lines within quote blocks

### ISSUE THREAD

**Issue by dionlarson** [vmg/redcarpet#550]
Quote blocks do not respect empty lines from nested, fenced code blocks. Instead, the empty line escapes the quote block and the closing ``` just opens a new fenced code block

**I'm trying to get this:**

``````
> This is a test of code blocks in quote blocks...
>
```
import Foundation

func testFunction() {

}
```
>
> Is this is still in a block?
``````

**To produce:**

> This is a test of code blocks in quotes...
> 
> ```
> import Foundation
> 
> func testFunction() {
> 
> }
> ```
> 
> Is this is still in a block?

**Instead, it escapes the quote block, prematurely ends the fenced code block, and opens a new fenced code block where it should have escaped the previous fenced code block:**

> This is a test of code blocks in quotes...
> 
> ```
> import Foundation
> ```

func testFunction() {

}

```
>
> Is this is still in a block?
```

**I can only get it working by using four-space code blocks (with an extra fifth space for the quote block) or by inserting `>` on each empty line in the fenced code block like this:**

``````
> This is a test of code blocks in quote blocks...
>
```
import Foundation
>
func testFunction() {
>
}
```
>
> Is this is still in a block?
``````

The only extension I have enabled is `fenced_code_blocks`. Is there another extension that might fix this issue or am I stuck with adding `>` to empty lines in the fenced code blocks?

**Comment by robin850** [comment]
Hi @dionlarson,

Actually, this is working as expected, block-quotes can be represented with a single `>` and every lines under it will be included inside the block-quote until an empty line is found. This is what's happening here ; if you want to include your code block inside the block-quote, just do:

~~~
> This is a test of code blocks in quote blocks...
>
> ```
> import Foundation
>
> func testFunction() {
>
> }
> ```
>
> Is this is still in a block?
~~~ 

Thanks for spotting this, it can be useful for someone else in the future and sorry for the very late answer ! Feel free to ask if you have any other question ! :-)
