### ISSUE TITLE
missing handling of left and right double quotation mark

### ISSUE THREAD

**Issue by LiranRomSamanage** [vmg/redcarpet#551]
Hi,

Thanks for the great gem

I'm using - Redcarpet::Markdown.new(Redcarpet::Render::HTML).render

The render didn't convert the left and right double quotation mark into HTML codes
&#8220; - for left one
&#8221; - for right one.

I've converted the result by myself.

Liran

**Comment by robin850** [comment]
Hi @LiranRomSamanage,

I think what you're looking for is the `SmartyPants` render, this is not a built-in feature of the `HTML` render. You can try the following:

~~~ruby
class HTMLWithPants < Redcarpet::Render::HTML
  include Redcarpet::Render::SmartyPants
end

Redcarpet::Markdown.new(HTMLWithPants).render("It's awesome")
~~~

Let me know if I misunderstood your problem and we can reopen the ticket, thanks !
