### ISSUE TITLE
unable to convert "\xCF" from ASCII-8BIT to UTF-8 

### ISSUE THREAD

**Issue by wilsonmar** [vmg/redcarpet#553]
I am getting this message with the following after running 
$ gem install redcarpet
Building native extensions.  This could take a while...
Successfully installed redcarpet-3.3.4
Parsing documentation for redcarpet-3.3.4
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/redcarpet.bundle, skipping
Done installing documentation for redcarpet (0 sec).
1 gem installed

I am using MacOSX El Capitan on standard Terminal.
ruby 2.0.0p0 (2013-02-24 revision 39474) [x86_64-darwin15.3.0]

**Comment by robin850** [comment]
Hi @wilsonmar,

This looks like this is an issue related to RDoc, not to Redcarpet (see https://github.com/rdoc/rdoc/issues/195) ; are your running an older version of RDoc than 4.0.1 ? If yes, update it and try again to run `gem install redcarpet`.

If the problem persists and it's Redcarpet which is at fault, please let me know and we can reopen this ticket.

Thanks !

**Comment by LittleSakana** [comment]
rdoc --version
5.0.0
but the problem persists
