### ISSUE TITLE
Use :safe_links_only only for automatic links

### ISSUE THREAD

**Issue by hkdobrev** [vmg/redcarpet#556]
I think the `:safe_links_only` should be used only for automatic linking. So when there is text like:

> Chat with us on irc://example.com/room

It must not be rendered as link, because `irc://` schema is not in the safe links.

However when rendering an actual Markdown link like:

> Chat with us on [#room](irc://example.com)

The link should be rendered. All links with the `[anchor text](URI)` should be rendered. Otherwise this is quite limiting.

Of course all attributes should be escaped even the `href` attributes in the `[]()` links.

So I think this should stay: https://github.com/vmg/redcarpet/blob/df1b85d77fc9c962237ca48b498395c40d012a52/ext/redcarpet/html.c#L89-L92

But this should not check for safe URI schemas: https://github.com/vmg/redcarpet/blob/df1b85d77fc9c962237ca48b498395c40d012a52/ext/redcarpet/html.c#L329-L330

A real world example from GitHub:
- [Raw Markdown (see Community)](https://raw.githubusercontent.com/composer/composer/40c14709f79f9d7ea35ac969cfbd7f41beb525bb/README.md)
- [Rendered Markdown with missing irc:// links](https://github.com/composer/composer/blob/40c14709f79f9d7ea35ac969cfbd7f41beb525bb/README.md#community)

**Comment by hkdobrev** [comment]
Here is a quick test case:

``` ruby
#!/usr/bin/env ruby

require 'redcarpet'

renderer = Redcarpet::Render::HTML.new(render_options = {
    # safe_links_only: true
})

markdown = Redcarpet::Markdown.new(renderer)

print markdown.render("[freenode](irc://irc.freenode.org/composer)")
```

Expected: `<p><a href="irc://irc.freenode.org/composer">freenode</a></p>` with both safe links option enabled or not.

Actual: `<p>[freenode](irc://irc.freenode.org/composer)</p>` when safe links option is enabled.

**Comment by robin850** [comment]
Hi @hkdobrev,

Thanks for the proposal ! Actually it's pretty hard to find a behavior that fits every cases. I guess that historically this option was added to make sure that you can take any user input for instance and return an HTML content that is safe for any user to read. If you want to mimic the behavior you described, you can create a custom render object like this:

~~~ruby
class CustomRender < Redcarpet::Render::HTML
  def autolink(link, link_type)
    if link.start_with?("#", "/", "http://", "https://", "ftp://", "mailto:")
      return %(<a href="#{link}">#{link}</a>)
    else
      return link
    end
  end
end
~~~

Thus, it's like enabling `safe_links_only` but only for auto-linking. And by the way, I think that you'll have to use the chevron syntax if you want to auto-link an `irc://` URL anyway. Hope it can help you ! :-)
