### ISSUE TITLE
underscores in email addresses are not rendered correctly

### ISSUE THREAD

**Issue by mehulkar** [vmg/redcarpet#558]
With these settings:

```ruby
opts = {
  filter_html: true,
  safe_links_only: false
}
renderer = Redcarpet::Render::HTML.new(opts)
extensions = {
  autolink: true
}
@markdown_renderer = Redcarpet::Markdown.new(renderer, extensions)
```

I'm trying to render this:

```md
x_b_and_c@bar.com
```

But it gets rendered as:

```html
x<em>b</em><a href="mailto:and_c@bar.com">and_c@bar.com</a>
```

I've also tried these in markdown:

```
<x_b_and_c@bar.com>

[x_b_and_c@bar.com](mailto:x_b_and_c@bar.com)

<x\_b\_and\_c@bar.com>

x\_b\_and\_c@bar.com
```

None of them seem to produce the right output, which should be this:

```html
<a href="mailto:x_b_and_c@bar.com">x_b_and_c@bar.com</a>
```

**Comment by robin850** [comment]
Hi @mehulkar,

Yep, this is a known bug (#402), I didn't look in depth at it but I hope to be able to soon. Waiting this to be resolved, you can enable the `:no_intra_emphasis` option on your `Redcarpet::Markdown` object as a turnaround.

Thanks for reporting anyway ! :-)

**Comment by mehulkar** [comment]
ah got it, thanks @robin850!
