### ISSUE TITLE
Support for latex equations

### ISSUE THREAD

**Issue by o9000** [vmg/redcarpet#559]
Many wikis support rendering of Latex equations by just including a MathJax or KaTeX JavaScript file in the header. Then equations embedded between "$" (inline) or "$$" (block) are processed when the page is loaded.

Unfortunately this works poorly in Markdown, since Latex uses heavily "_", which is interpreted as emphasis.

It would be great if there was an option in redcarpet to treat all content between one or two dollar signs verbatim (similar to "`").

**Comment by robin850** [comment]
Hi @o9000,

You can already mimic such behavior, not through an option but through a custom render object, like:

~~~ruby
class CustomRender < Redcarpet::Render::HTML
  def block_code(code, lang)
    if lang == 'latex'
      return code
    else
      return %(<code class="#{lang}"><pre>#{code}</pre></code>)
    end
  end

  def codespan(code)
    if code.start_with?("$$") and code.end_with?("$$")
      return code
    else
      return %(<code>#{code}</code>)
    end
  end
end

# And then
parser = Redcarpet::Markdown.new(CustomRender, fenced_code_blocks: true)
~~~

And inside your Markdown, document, you can add LaTeX inline equations wrapping dollar signs around backticks and you can add block equations through fenced code blocks specifying `latex` as the langugage. Thus, underscores won't be parsed as emphasis for instance.

Hope it can help you ! :-) Thanks !

**Comment by o9000** [comment]
Excellent! Thanks.
