### ISSUE TITLE
Redcarped incorrectly handles emails with underscore char

### ISSUE THREAD

**Issue by kayrus** [vmg/redcarpet#561]
I.e. redcarpet hides `<a_bc@def.com>` (`<p><a_bc@def.com></p>`)
but shows `<abc@def.com>` (`<p><a href="mailto:abc@def.com">abc@def.com</a></p>`)

**Comment by robin850** [comment]
Hi @kayrus,

Thanks for reporting this issue ; actually, this is a known bug (see #402), I will try to have a look at that as soon as possible. You can enable the `:no_intra_emphasis` instantiating the `Redcarpet::Markdown` object as a temporary work-around.
