### ISSUE TITLE
Where I can find the markdown reference that redcarpet implements? (Question)

### ISSUE THREAD

**Issue by vizcay** [vmg/redcarpet#564]
Hi, there are minor differences between markdown implementations syntax.. where I can find the specification that redcarpet adheres to? Thanks

**Comment by robin850** [comment]
Hi @vizcay,

We try to be as much as possible close to the behavior of the original `Markdown.pl` implementation. Anyway, we are compliant with the [Markdown conformance suite](https://github.com/vmg/redcarpet/tree/4f3a899191633a1da68156c925ff9eaee6d0b8f0/test/MarkdownTest_1.0.3/Tests) at least.

This suite is not complete, thus, there are some features that are present in the spec that we don't yet implement like [e-mail entity-encoding](https://github.com/vmg/redcarpet/issues/127).

I hope this answers your question, thanks ! :-)
