### ISSUE TITLE
How do I add extra tags to Redcarpet?

### ISSUE THREAD

**Issue by wraithseeker** [vmg/redcarpet#567]
I want to be able to detect custom markdown syntax that has been written, similar to how Stackexchange detects spoiler text.

`>! some text here
`
Is it possible to do this with Redcarpet? Something like  detecting ( >! ) . 

I don't quite understand the part on https://github.com/vmg/redcarpet#and-you-can-even-cook-your-own

**Comment by robin850** [comment]
Hi @wraithseeker,

I'm wondering whether we should not re-write this part of the README ; nobody seems to understand that you can cook your own Markdown render object with Redcarpet. Actually that's fairly easy, you can define, on your custom render object, a callback method that will be called anytime the element it represents is found in the document.

In your case, you want to do a special treatment for blockquotes, so:

~~~ruby
require 'redcarpet'

class CustomRender < Redcarpet::Render::HTML
  def block_quote(quote)
    # That's pretty particual here but the `quote`
    # parameter doesn't contain the raw Markdown, but
    # the already parsed Markdown so it is HTML from here.
    if quote.start_with?("<p>!")
      return %(<div class="spoiler">#{quote.sub('<p>! ', '')}</div>)
    else
      return %(<blockquote>#{quote}</blockquote>)
    end
  end
end

# Then pass it when instantiating your Markdown parser
# and call `render` with your document as usual
parser = Redcarpet::Markdown.new(CustomRender.new)
parser.render(my_markdown_document)
~~~

I hope it helps you, thanks for spotting this ! I'm giving this is a close, feel free to ask if you have further questions.
