### ISSUE TITLE
Are there any ways to set footnote title?

### ISSUE THREAD

**Issue by mizunashi-mana** [vmg/redcarpet#568]
redcarpet render can not support footnote title, can it?

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title is very useful.  Modern browsers show tooltip for links.

Example:

```html
<a href='#' title='jump page top'>#</a>
```

However, redcarpet html render outputs links without title.

Moreover, I'm writing custom render (e.g. [MoinMoin](https://moinmo.in/) render) using redcarpet.
MoinMoin has Footnote macro (see https://moinmo.in/HelpOnMacros#Others).
Can redcarpet support such footnote type?
Current APIs seem not to provide this support. (I understood this support is very important and very difficult...)

If we have any solutions, I suggest.

**Comment by robin850** [comment]
Hi @mizunashi-mana,

I'm not sure to understand your problem but maybe the solution is to create a custom render object and redefine the footnote definition hook, like this:

~~~ruby
class CustomRender < Redcarpet::Render::HTML
  def footnote_def(content, number)
    content = content.split(/<\/?p>/)[1]

    %(<p>#{content} <a href="#fnref#{number}" title="Jump page top">#</a></p>)
  end
end

# Then use it instantiating your parser
parser = Redcarpet::Markdown.new(CustomRender.new, footnotes: true)
~~~

Let me know if I'm missing something.

**Comment by mizunashi-mana** [comment]
@robin850 Thanks for response.  Sorry, I'm missing on previous comment.

For example, we try to set footnote **reference** title:

```ruby
class CustomRender < Redcarpet::Render::HTML
  def footnotes(content)
     %(<div class="footnotes"><hr><ol>#{content}</ol></div>)
  end

  def footnote_def(content, num)
     content = content.split(/<\/?p>/)[1]

     %(<li id="fn#{num}">#{content}&nbsp;<a href="#fnref#{num} rev="footnote">&#8617;</a></li>)
  end

  def footnote_ref(num)
     %(<sup id="fnref#{num}"><a href="#fn#{num}" rel="footnote" title="need footnote content">num</a></sup>)
  end
end
```

We try to get footnote content on footnote_ref, but we find needing backtrack for it.

ref: https://github.com/vmg/redcarpet/blob/master/ext/redcarpet/html.c#L606

In the moinmoin case:

```ruby
class MoinMoinRender < Redcarpet::Render::Base

# ~~~
# Other methods
# ~~~

  def footnotes(content)
     # nothing to do
  end

  def footnote_def(content, num)
     # nothing to do
  end

  def footnote_ref(num)
      '<<FootNote(need footnote content)>>'
  end
end
```

Can we create such render?

**Comment by robin850** [comment]
@mizunashi-mana : Okay, that one is pretty trick then :smile: :

~~~ruby
class MoinMoinRender < Redcarpet::Render::HTML
  def initialize(extensions = {})
    @footnotes = {}

    super(extensions)
  end

  # The problem is that callbacks are called in the order
  # they appear inside the document so we need to keep
  # a reference to footnotes' content somewhere ...
  def footnote_def(content, num)
    @footnotes[:"footnote_#{num}"] = content
  end

  # .. Then insert place-holders for inserting the contents
  def footnote_ref(num)
    "<<%{footnote_#{num}}>>"
  end

  # And once every footnotes have been read, we can replace
  # all the place-holders with their associated footnote's content.
  def postprocess(full_document)
    full_document % @footnotes
  end
end
~~~

Hoping it is what you were looking for.

**Comment by mizunashi-mana** [comment]
@robin850 Thx! It's amazing!

Actually, I fixed this:

```ruby
class MoinMoinRender < Redcarpet::Render::HTML
  def initialize(extensions = {})
    @footnotes = {}

    super(extensions)
  end

  def footnote_def(content, num)
    @footnotes[:"footnote_#{num}"] = content
  end

  def footnote_ref(num)
    "<<%{footnote_#{num}}>>"
  end

  # Escape special chars
  def preprocess(full_document)
    full_document.gsub('%', '%%')
  end

  def postprocess(full_document)
    full_document % @footnotes
  end
end
```

This works great.  Very thanks @robin850

**Comment by robin850** [comment]
No problem, happy that it works for you ! :-)
