### ISSUE TITLE
Whitespace messes up markdown parsing

### ISSUE THREAD

**Issue by burlesona** [vmg/redcarpet#571]
Currently red carpet fails to parse italics / bold if there is whitespace at the end of it. EG:

Eg. given input:
```
"*some italics *and some more non-italics text"
```
This should output:
```
"<p><em>some italics </em>and some more non-italics text</p>\n"
```
But instead it outputs:
```
"<p>*some italics *and some more non-italics text/</p>\n"
```

I realize that leaving a space in the wrong place looks ugly, but among input in my app I'm seeing it's a fairly common user error, and I would still expect the parser to treat anything between italics as being emphasized.

**Comment by robin850** [comment]
Hi @burlesona,

The original Markdown spec doesn't say anything about that case but CommonMark is clearly stating that the right delimiter of an emphasis [should not be preceded by a whitespace](http://spec.commonmark.org/0.25/#right-flanking-delimiter-run) and testing a few other implementations (Markdown.pl, CommonMark, Kramdown), they are not supporting this syntax neither.

I'm giving this a close but thanks anyway !
