### ISSUE TITLE
Release 3.3.5 version

### ISSUE THREAD

**Issue by gogiel** [vmg/redcarpet#572]
There are a lot of changes since the last release https://github.com/vmg/redcarpet/compare/v3.3.4...master

Is it ready to be released? Is there a policy when to release a new version?

Thanks

**Comment by robin850** [comment]
Hi @gogiel,

I'm sorry I didn't spend much time on this project recently but I hope to release version 3.4.0 as soon as possible. There are still [some issues](https://github.com/vmg/redcarpet/milestones/3.4.0) open before the release though.

I'm giving this a close but will comment when 3.4 will be out. Thanks ! :-)

**Comment by robin850** [comment]
3.4.0 has been released ; sorry for looooooong time it took ! :heart: Merry Christmas and happy new year !
