### ISSUE TITLE
PrismJS compatibility

### ISSUE THREAD

**Issue by MiguhRuiz** [vmg/redcarpet#577]
Is there any option flag in order to generate the classes that Prism need?

[PrismJS - Basic Usage](http://prismjs.com/#basic-usage)

**Comment by robin850** [comment]
Hi @MiguhRuiz,

Nope, sorry, there's not such option available but you can implement a custom render object to output the class:

~~~ruby
class CustomRender < Redcarpet::Render::HTML
  def block_code(code, lang)
    %(<pre><code class="language-#{lang}>#{code}</code></pre>)
  end
end
~~~

I'm closing this issue but thanks for raising this, it could be useful for people in the future. :-)
