### ISSUE TITLE
RFC: is it possible to extend Redcarpet to do rowspan/colspan tables?

### ISSUE THREAD

**Issue by sixtyfive** [vmg/redcarpet#584]
Hi, and first off, sorry that this is neither a bug nor a feature request. 

I'm currently trying to decide whether to use asciidoc or Markdown for a project. Markdown would be the better choice for its greater simplicity and readability. Unfortunately, the project needs both rowspan and colspan features for tables, which e.g. asciidoctor provides. 

The ideal situation would be if a table generator could be used (i.e., click a table together like with http://www.tablesgenerator.com/text_tables or perhaps even http://asciiflow.com/) and then paste the output into the document.

Do you think it (perhaps utilizing code fencing?) it would be feasible to get Redcarpet to do something like this?

**Comment by robin850** [comment]
Hi @sixtyfive,

Nope, I'm sorry but Redcarpet (and Markdown in general) doesn't provide any support for rowspan or colspan inside tables.

This is a very personal thought but in general, I tend to avoid ASCII representation of tables. They aren't reliable, they don't look nice when tables get bigger, you always struggle against something that isn't supported by the markup but that would make your table look the way you want (rowspan is a good example).

ASCII representations of tables are useful for *very* simple cases but they become a PITA when you are dealing with a large amount of data or if you want to represent them in an uncommon way.

Thanks anyway for spotting this, this can be useful for someone else in the future ! :-)

**Comment by sixtyfive** [comment]
@robin850, thank you for your answer including the personal thoughts!

For our specific use case we've decided that the ASCII tables as produced by [tablesgenerator.com](tablesgenerator.com/text_tables) work really well, especially because that website makes it so easy to create them (which also negates some of your concerns regarding ASCII tables). I've since written a parser for them that builds a Hash representation and then outputs an HTML table by way of Nokogiri. It takes less than two tenths of a second even for something like a 5x20 table with various row- and colspans, so it's good enough for me.

Now the challenge remains to call that from within a Markdown processor somehow. I've received some info on that from the Kramdown people where it seems possible to write a "style" that feeds the table into my parser as though it was code that needed to be highlighted. Would the same thing be possible in Redcarpet and how would one go about it? Are there any docs?

**Comment by robin850** [comment]
I'm not sure to understand what you want to do but it is possible to customize the output generated by Redcarpet by creating a custom render object that inherits from `Redcarpet::Render::HTML`. As far as I can understand, you certainly want to do some processing inside the `preprocess` method. You can checkout [the README](https://github.com/vmg/redcarpet#and-you-can-even-cook-your-own) for further information.

**Comment by sixtyfive** [comment]
Hi again! I finally decided to go with Kramdown, mostly because they support CSS classes and ids which I, in all likelyhood, won't be able to do without for this project. The thing I wanted to do is explained in [the respective ticket over at Kramdown](https://github.com/gettalong/kramdown/issues/388#issuecomment-260380155) in case anyone ever comes by this thread here who is looking for something similar. Also, a crude but possible solution is given there now.
