### ISSUE TITLE
extending Markdown syntax, similar to github issue references

### ISSUE THREAD

**Issue by jnicho02** [vmg/redcarpet#585]
Apologies if there is an example of this already. I could only see the example of overriding existing syntax.

On my site, I would like to add Markdown syntax so that a hash+number links to a record. This is similar to github's issue references https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf "Any number that refers to an Issue or Pull Request will be automatically converted into a link." 

Is this possible?

**Comment by robin850** [comment]
Hi @jnicho02,

Yes, this is totally possible, you just need to hook into the `paragraph` method like this:

~~~ruby
class CustomRender < Redcarpet::Render::HTML
  def paragraph(text)
    text.gsub!(/\#([0-9]+)/) do |match|
      %(<a href="link/to/issue/#{match[1..-1]}">#{match}</a>")
    end

    %(<p>#{text}</p>)
  end
end
~~~

Hope this helps you, feel free to comment if you don't understand something ! :-)

**Comment by jnicho02** [comment]
thank you. It works a treat.
