### ISSUE TITLE
Example of reusing parser between parses

### ISSUE THREAD

**Issue by brchristian** [vmg/redcarpet#588]
In the docs, you write that "The `Redcarpet::Markdown` object is encouraged to be instantiated once with the required settings, and reused between parses."

Would it be possible to provide an example of best practices for this? Currently my app has a method in the application_helper.rb like so:

```ruby
def render_markdown(text)
  Redcarpet::Markdown.new(Redcarpet::Render::HTML).render(text).html_safe
end
```

Is this instantiating a new renderer every time it’s called (multiple times per pageview)? Is there a better way of going about this – say, by defining a constant in the app initializer?

I’m curious for my own case, and it might be helpful to add any relevant best practices to the documentation as well.

**Comment by robin850** [comment]
Hey @brchristian,

Sorry for the late answer ! Actually, that's fairly easy, you just need to store your render object in a class variable inside your helper module, for instance:

~~~ruby
module ApplicationHelper
  def render_markdown(text)
    @@parser ||= Redcarpet::Markdown.new(Redcarpet::Render::HTML)

    @@parser.render(text).html_safe
  end
end
~~~

Then, the parser will be instantiated only once. :-) Thanks for raising that question, I'm giving this a close, feel free to comment if you have further questions !

**Comment by brchristian** [comment]
@robin850 Makes total sense – and thanks for the reply. Cheers!
