### ISSUE TITLE
some tables rendered in incorrect way

### ISSUE THREAD

**Issue by nvoynov** [vmg/redcarpet#590]
Hi,

I have a problem with some tables but I can't understand it is RedCarpet bug or not. You can see attached file [core.req.txt](https://github.com/vmg/redcarpet/files/643725/core.req.txt) that have few tables and incorrect rendering. The first table renders as correct table, the second doesn't.

I use followed options `{ autolink: true, tables: true, with_toc_data: true, fenced_code_blocks: true }`

Before I started [my own simple server](https://github.com/nvoynov/minireq-site) to serve my markdown documents, I used gitbook and didn't have any issues with tables.

**Comment by nvoynov** [comment]
There is a simplest example bellow
```ruby
require 'redcarpet'
markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :tables => true)

text = <<END

# First table

Name | Type | M | Desc
---- | ---- | - | ----
Name | Type | M | Desc

# Second table

header 1 | header 2
-------- | --------
cell 1   | cell 2
cell 3   | cell 4

END

puts markdown.render(text)
```

That produces the next output

```html
<h1>First table</h1>

<p>Name | Type | M | Desc
---- | ---- | - | ----
Name | Type | M | Desc</p>

<h1>Second table</h1>

<table><thead>
<tr>
<th>header 1</th>
<th>header 2</th>
</tr>
</thead><tbody>
<tr>
<td>cell 1</td>
<td>cell 2</td>
</tr>
<tr>
<td>cell 3</td>
<td>cell 4</td>
</tr>
</tbody></table>
```

**Comment by nvoynov** [comment]
After this question, I gave up with all markdown gems and started to use pandoc and still happy with.

**Comment by pasnox** [comment]
I would like too, the problem is that gitlab do use that one for it's wiki pages, so the markdown library has to match in my editor 😣 And arguing how long your question has been unanswered, I should not wait for one as well... Thanks for the hint thought

**Comment by robin850** [comment]
Hello there,

Sorry for the very late answer. This might be far too late but to give you an answer, just in case people might have these issues:

@nvoynov : Your executable snippet currently works correctly on Redcarpet 3.5.1 so it looks like this has been fixed.

@pasnox : You were actually passing the `:tables` option to the wrong object. It must be passed to the `Redcarpet::Markdown` constructor and not the render's one.

I'm giving this a close. Thanks for reporting anyway.
