### ISSUE TITLE
Allow arbitrary info strings in fenced code blocks

### ISSUE THREAD

**Issue by szeiger** [vmg/redcarpet#592]
This is related to https://github.com/vmg/redcarpet/issues/187 but it's a problem with the parser, not the renderer. According to the [CommonMark spec](http://spec.commonmark.org/0.27/#fenced-code-blocks) the only restriction on info strings is that they must not contain backtick characters.

In github's rendering of https://github.com/szeiger/ornate/blob/afd538c599a0e6bb767ac61625ce08f2121f91fd/doc/src/markdown.md all blocks with non-trivial info strings are messed up, the same goes for nested blocks, which may be the same or a different problem.

(I hope this is the right place to file this issue. According to https://github.com/github/markup README files are parsed with redcarpet. Note that when pasting the offending Markdown content into a github issue and clicking "Preview", it is parsed correctly.)

**Comment by robin850** [comment]
Hello,

Sorry for the very late reply but I'm giving this a close for the following reasons:

* GitHub is no longer using Redcarpet to render README files
* Changing the way we parse the info string on fenced code blocks might break existing documents
* If you're using Redcarpet on your own, you can always resort to a custom render object to implement this behavior

Thanks for reporting anyway !
