### ISSUE TITLE
Request: Support Pandoc-style "span-only links"

### ISSUE THREAD

**Issue by Porges** [vmg/redcarpet#595]
Pandoc has a markdown extension called [`bracketed_spans`](http://pandoc.org/MANUAL.html#extension-bracketed_spans). It allows you to have links without targets, so that you can apply arbitrary attributes:

    [this is not a link]{this="not-link"}

These are then rendered as `<span/>`s with the attributes applied.

I'd really like this in redcarpet (and thus GitHub) because it makes (human) language tagging much simpler&mdash;the only way to achieve this is at the moment is to drop to HTML-syntax `<span lang="foo">in language foo</span>`, which is not as nice as sticking to Markdown 🙂 (the equivalent
being `[in language foo]{lang="foo"}`).

Motivation: Tagging language in HTML is important due to Han unification (among other things), where [the rendering of a particular character depends on what the target language is](https://en.wikipedia.org/wiki/Han_unification#Examples_of_language-dependent_glyphs):

![image](https://cloud.githubusercontent.com/assets/12575/21705161/50ec8654-d412-11e6-85b5-1e6fb72b498d.png)

Thanks!

**Comment by robin850** [comment]
Hi @Porges,

Sorry but actually the "philosophy" in Redcarpet is that we try to avoid as much as possible to implement feature that can't be easily achieved through HTML. Markdown isn't intended to replace HTML but work with it. You can still do:

~~~html
<span this="not-link">This is not a link</span>
~~~

Which is not much longer than:

~~~markdown
[this is not a link]{this="not-link"}
~~~

Also if you were requesting that change to be able to use it on GitHub, Redcarpet isn't their Markdown parser anymore.

I'm giving this a close but thank you very much for the proposal anyway !
