### ISSUE TITLE
Skip paragraph (<p>) tag?

### ISSUE THREAD

**Issue by xanview** [vmg/redcarpet#596]
```
(dev)> renderer = Redcarpet::Render::HTML.new
=> #<Redcarpet::Render::HTML:0x007fc8b9a86f18 @options={}>
(dev)> Redcarpet::Markdown.new(renderer, {}).render('asd') 
=> "<p>asd</p>\n"
```

Is there any way to tell Redcarpet to not surround the formatting in a p tag? - I want to add a link to a form label and the p tag is introducing undesired new lines.

**Comment by robin850** [comment]
Hi @xanview,

There's no built-in feature to disable surrounding of paragraphs but you can implement a custom render like:

~~~ruby
class CustomRender < Redcarpet::Render::HTML
  def paragraph(text)
    text
  end
end
~~~

I'm giving this issue a close but thanks for spotting this anyway ! :-)
