### ISSUE TITLE
Punctuation is not correctly dropped from toc_data

### ISSUE THREAD

**Issue by xavdid** [vmg/redcarpet#602]
```ruby
markdown.render('## tl;dr')
=> "<h2 id=\"tl-dr\">tl;dr</h2>\n"
```

Per [this answer](http://stackoverflow.com/a/38507669/1825390), punctuation is stripped from the anchor. I've confirmed GH processes it this way [here](https://gist.github.com/xavdid/1395d979457ce2e0babb1106888072c0#tldr). So, the resulting id of the above code should be `tldr`. I believe the `;` is getting erroneously replace with a space. 

Thanks a bunch!

**Comment by robin850** [comment]
Hello @xavdid,

GitHub doesn't use Redcarpet as its Markdown processor anymore. This is the expected output ; Redcarpet replaces punctuation elements and spaces with dashes.

I'm giving this a close but thanks for reporting anyway ! :-)
