### ISSUE TITLE
Mixing lists

### ISSUE THREAD

**Issue by FiloSpaTeam** [vmg/redcarpet#603]
Hi guys, i need to understand what is wrong with this text:
```
1. lol
2. lol
3. lol

---

1. lol
* lol
2. lol

---

1. lol

* lol

2. lol
```

It renders wrong, like:
```
1. lol
2. lol
3. lol

---

1. lol
2. lol
3. lol

---

1. lol

* lol

1. lol
```

:D Thanks

**Comment by dddanielpena** [comment]
android test

**Comment by mscherer11** [comment]
Make sure you are indenting your sub-bullets.  Otherwise Markdown will continue the ordered list.

1. lol
    * lol
2. lol

**Comment by FiloSpaTeam** [comment]
It solves but, your opinion:
- why on Diaspora (that use this plugin, i checked in Gemfile and relative usage) my code above works? xD

Many thanks :+1:

**Comment by deckar01** [comment]
This seems to be the behavior in most markdown engines. daringfireball doesn't really cover this case, but it does seem to suggest that ordered list don't really care about list prefix, just the indentation level.

A quick peek at Diaspora's markdown pipeline did not indicate they were doing anything special. Maybe something is cleaning it up on the front end.

**Comment by FiloSpaTeam** [comment]
Ok thanks :dancer:

**Comment by robin850** [comment]
(Hi there ! I take the liberty to give this a close ; sorry for not answering and thanks for reporting and answering guys ! 😊 )
