### ISSUE TITLE
List Numbering Discrepancy With Github When Bolding Items

### ISSUE THREAD

**Issue by chutch1994** [vmg/redcarpet#606]
I just wanted to point out a discrepancy between how Redcarpet and Github handle bolding a line in an ordered list.

Whenever you enter the following markdown...

````
**1. first**

2. Second

3. Third
````

And try to render it as HTML in Redcarpet, you get the following HTML...

````
<p>
  <strong>1. First</strong>
  <ol>
    <li>Second</li>
    <li>Third</li>
  </ol>
</p>
````

This makes the numbering off in that it would go (1, 1, 2) and not (1, 2, 3).

However, on Github, it starts the numbering at 2 so that the sequence is correct.

````
<p>
  <strong>1. First</strong>
  <ol start="2">
    <li>Second</li>
    <li>Third</li>
  </ol>
</p>
````

It's certainly an edge case, but I just wanted to point it out.

**Comment by robin850** [comment]
Hi there,

Sorry for the late answer but actually, this is something we can't really change. GitHub is now using another flavor of Markdown (CommonMark) but according to [the spec](https://daringfireball.net/projects/markdown/syntax#list) of the "plain old" Markdown, people can write things like:

~~~
3. Hello
6. World
~~~

And still get a list that starts at one.

I'm giving this a close but thanks for reporting.
