### ISSUE TITLE
Relative links rendered with incorrect directory path

### ISSUE THREAD

**Issue by PreciselyAlyss** [vmg/redcarpet#614]
#### Expected behavior

When adding a link with a relative path, I expect it to render display and link to the directory path I indicated. 

`[/v3/orders/{order_id}/transactions](/api/v3/openapi-v3.html#gettransactions/)` should provide `https://domain.com/api/v3/openapi-v3.html#gettransactions`. 

#### Actual behavior

Links that contain `.html` instead of a relative directory path strip the part of the url so the link for `[/v3/orders/{order_id}/transactions](/api/v3/openapi-v3.html#gettransactions/)` becomes `https://domain.com/v3/openapi-v3.html#gettransactions`. 

#### Steps to reproduce

This above behavior has been seen with [middleman](https://github.com/middleman/middleman) with [Slate](https://github.com/lord/slate). 

Attempts to troubleshoot have included adding a trailing slash and removing it or changing the placement. 

- `[/v3/orders/{order_id}/transactions](/api/v3/openapi-v3.html/#gettransactions)`
- `[/v3/orders/{order_id}/transactions](/api/v3/openapi-v3.html#gettransactions)`
- `[/v3/orders/{order_id}/transactions](/api/v3/openapi-v3.html#gettransactions/)`

Middleman config file: 
```ruby
# Markdown
set :markdown_engine, :redcarpet
set :markdown,
    fenced_code_blocks: true,
    smartypants: true,
    disable_indented_code_blocks: true,
    prettify: true,
    tables: true,
    with_toc_data: true,
    no_intra_emphasis: true

# Sitemap
page "/sitemap.xml", :layout => false

# Assets
set :css_dir, 'stylesheets'
set :js_dir, 'javascripts'
set :images_dir, 'images'
set :fonts_dir, 'fonts'

# Activate the syntax highlighter
activate :syntax

activate :autoprefixer do |config|
  config.browsers = ['last 2 version', 'Firefox ESR']
  config.cascade  = false
  config.inline   = true
end

# Github pages require relative links
activate :relative_assets
set :relative_links, true

# Build Configuration
configure :build do
  # If you're having trouble with Middleman hanging, commenting
  # out the following two lines has been known to help
  activate :minify_css
  activate :minify_javascript
  # activate :relative_assets
  # activate :asset_hash
  # activate :gzip
end

helpers do
  require './lib/toc_data.rb'
end
```

**Comment by robin850** [comment]
Hello @PreciselyAlyss,

I tried to create a new Slate project with your build and inserting this link:

~~~markdown
[/v3/orders/{order_id}/transactions](/api/v3/openapi-v3.html#gettransactions/)
~~~

But it generates a link to `localhost:4567/api/v3/openapi-v3.html#gettransactions/`. Also, there is no `./lib/toc_data.rb` file so I guess that's a custom file that you've defined but the problem may come from here.

Could you please isolate an example Slate application or Redcarpet reproduction script to showcase the problem ? I don't think that's a Redcarpet problem ; [this line](https://github.com/middleman/middleman/blob/63504f13bbc0dd8c8dd62f493edcfaa8637d6983/middleman-core/lib/middleman-core/renderers/redcarpet.rb#L89) looks really suspicious but let's wait, I may be wrong.

Thanks for reporting anyway ! :-)

**Comment by audygit** [comment]
thanks

**Comment by robin850** [comment]
Hello there,

As you might have noticed, this project has pretty limited resources. If you are still experiencing this issue, please do provide a reproduction snippet so we can isolate the problem and reopen this ticket if needed.

I'm giving this a close ; thanks.
