### ISSUE TITLE
Withspace in front of lines

### ISSUE THREAD

**Issue by Lubmes** [vmg/redcarpet#617]
I am making a poetry website and some poems start with whitespace in front of the line.

I know I can add `&nbsp;` but it's off course way better if I can just use spaces or maybe an excluded symbol like `~` or whatever. 

Could I use an option for that. Or write my own custom method that converts back and forth my special symbol between a `&nbsp;` and a "whitespace" in my forms / show?

Thanks.

**Comment by robin850** [comment]
Hi @Lubmes,

Could you please explain what's the point of this space ? Why don't you use CSS if you want to shift a bit the first letter ?

You could write a custom render object to handle the transformation of a space with a `&nbsp;` but Redcarpet won't help you the other way around to change your `&nbsp;` back in a space in your edit form.

**Comment by KjellMorgenstern** [comment]
Can this be closed?

**Comment by robin850** [comment]
Hi,

Yes, I'm going to give this a close ; thanks for the heads up @KjellMorgenstern.

Feel free to comment if we can be of any help and we can reopen if needed, @Lubmes.
