### ISSUE TITLE
[bug] genarate duplicated headers links hash

### ISSUE THREAD

**Issue by keiaihara** [vmg/redcarpet#629]
Its not working a tag hash.
If A header text is same as B header text, `href#` are duplicate , using `Redcarpet::Render::HTML.new(
    with_toc_data: true
 )`

I dont know why this problem happens...
I just guess It seems like no-check wherther each of headers is unique when generate headers link..

```html
:
<ul>
  <li>hoge1</li>
  <li>
     <ul>
        <li><a href="#part-ec2fb03c31af4bab">hoge</a><li>
     </ul>
<li>hoge2</li>
  <li>
     <ul>
        <li><a href="#part-ec2fb03c31af4bab">hoge</a><li>
     </ul>
</li>
:
<h2>hoge1</h2>
     <h3>hoge</h3>
     <p>xxxxxxxxxx</p>
<h2>hoge2</h2>
     <h3>hoge</h3>
     <p>xxxxxxxxxx</p>
:
```

Tks help us

**Comment by robin850** [comment]
Hello @keiaihara,

Please see this comment: https://github.com/vmg/redcarpet/issues/307#issuecomment-261793668.

Thanks for reporting anyway !

**Comment by kieaiaarh** [comment]
@robin850

gotcha!
I just think so it's.not worth maintenance cost.
I'll try custom render to handle duplicates.
Anyway, thanks 4 quick ur reply!
