### ISSUE TITLE
Email obfuscation

### ISSUE THREAD

**Issue by MrKickkiller** [vmg/redcarpet#631]
I'm using Redcarpet for parsing user-provided markdown content. 

I want to avoid that a user inputs an email address in simple text, and it coming up in plain text in the parsed view. So I want to obfuscate all email adresses to avoid spam bots.

| Raw html  | Condition  |
|---|---|
| `myemail@example.com`  | User input  |
| `<a href="mailto:myemail@example.com" rel="nofollow" target="_blank">myemail@example.com</a>` | Browser html  |
| `<a href="mailto:myemail@example.com" rel="nofollow" target="_blank">myemail@example.com</a>` | Curl |

Generated via the following ruby code
```ruby
@@html_renderer ||= Redcarpet::Markdown.new(
        Redcarpet::Render::HTML.new(
            escape_html: true,
            hard_wrap: true,
            link_attributes: {rel: 'nofollow', target: '_blank'},
            space_after_headers: true,
            fenced_code_blocks: true,
            safe_links_only: true
        ),
        autolink: true,
        superscript: true,
        disable_indented_code_blocks: true,
        tables: true,
        strikethrough: true
    )
```

Anyone that has an idea on how to efficiently achieve this?

**Comment by robin850** [comment]
Hello @MrKickkiller,

Sorry for the late answer ! You can actually implement a custom render object like this:

~~~ruby
class CustomRender < Redcarpet::Render::HTML
  def autolink(link, link_type)
    return if link_type == :email
   
    if @options[:link_attributes]
      default_attributes = @options[:link_attributes]
                            .map {|k, v| "#{k}=#{v}" }.join(" ")
      %(<a href="#{link}" #{default_attributes}>#{link}</a>)
    else
      %(<a href="#{link}">#{link}</a>)
    end
  end
end
~~~

Feel free to comment if you have further questions ; thanks for spotting this.
