### ISSUE TITLE
customizing rendering to add dynamic attributes to links

### ISSUE THREAD

**Issue by btc** [vmg/redcarpet#635]
I am trying to rewrite all `<a>` elements to include an `onclick` attribute that depends on the value of the `href` attribute. What's the best entrypoint for customization to pull this off?

Example:
``` html
<a href="http://www.example.com" onclick="trackOutboundLink('http://www.example.com'); return false;">Check out example.com</a>
```

**Comment by robin850** [comment]
Hello @btc,

This is actually pretty easy:

~~~ruby
class CustomRender < Redcarpet::Render::HTML
  def link(link, title, content)
    %(<a href="#{link}" onclick="func('#{link}')">#{content}</a>)
  end
end
~~~

You can find all the documentation about custom render classes in [the README file](https://github.com/vmg/redcarpet#and-you-can-even-cook-your-own).
