### ISSUE TITLE
How to preprocess the "src" value for img?

### ISSUE THREAD

**Issue by GildedHonour** [vmg/redcarpet#640]
Is it possible to preprocess/change the "src" value for all my img tags in a text? something like
```

     text = "dfsfdsfds [img src='something.jpg']aaa[/img]"
     res = markdown.preprocess(text, "img") {|img| img["src"] = "some_path/" + img["src"] }.  
                                  render
```

**Comment by GildedHonour** [comment]
up

**Comment by robin850** [comment]
Hello @GildedHonour,

Actually you are not using the Markdown syntax to render images so I'm not sure what you are trying to achieve here but you would have to define a custom render and use the `preprocess` hook and a regular expression to change the value. Something like that maybe:

~~~ruby
class CustomRender < Redcarpet::Render::HTML
  def preprocess(document)
    document.gsub!(%r{\[img src="([\w|\.]+)"\]([\w|\s]+)\[\/img\]}) do
      %(<img src="some_path/#{$1}" alt="#{$2}">)
    end

    document
  end
end
~~~

If you are using the regular Markdown syntax for image, then you can define the `image(source, title, alt_text)` callback and change the value of the `source` argument.

Sorry for the late answer but thanks for spotting this !
