### ISSUE TITLE
None of my extensions work?

### ISSUE THREAD

**Issue by 9mm** [vmg/redcarpet#643]
Hmm, I have a very basic use case and none of them are working...

```
Redcarpet::Markdown.new(Redcarpet::Render::HTML, { 
  filter_html: true,                               
  safe_links_only: true,                           
  link_attributes: {target: '_blank'}              
}).render(markdown)                                
```                                                
The only one that works is `autolink: true`, so I'm positive that it does see the extensions to begin with. But `filter_html` lets me inject custom HTML and script tags right into the output. `link_attributes` also does absolutely nothing.

**Comment by 9mm** [comment]
So the docs are just wrong then. It doesn't work like that at all.

Here's how I fixed it for people looking for this in the future

```
class CustomMarkdown

  def initialize
    @renderer = Redcarpet::Render::HTML.new(
      filter_html: true,
      safe_links_only: true,
      link_attributes: {target: '_blank'}
    )
  end

  def render(markdown)
    Redcarpet::Markdown.new(@renderer).render(markdown)
  end

end
```

**Comment by 9mm** [comment]
I see now there are `renderer` options and `markdown` extensions, they shouldn't be in the same list in the docs.. I see dozens of issues online cause of this

**Comment by robin850** [comment]
Hello @9mm,

Sorry for the late answer ! Actually, the README file properly makes the distinction between Markdown and render options but I agree that we can do a better job since most people won't carefully read the whole file but just trying to roughly skim it.

Thanks for spotting this anyway !
