### ISSUE TITLE
No script, no headers requested feature

### ISSUE THREAD

**Issue by mnlse** [vmg/redcarpet#653]
## Requested features
- A no <script> tag option
- no headers option

Please add it.

**Comment by robin850** [comment]
Hello @mnlse,

It's actually pretty easy to implement a custom render yourself and strip out the HTML tags that you want. Here's an example that will simply strip out `<script>` and `<header>` tags from your documents:

~~~ruby
require 'redcarpet'

class CustomRender < Redcarpet::Render::HTML
  def block_html(html)
    return nil if html.include?("<script")
    return nil if html.include?("<header")

    html
  end
end

markdown = <<~MD
Skyler,

<script>alert("I am the danger !")</script>
MD

puts Redcarpet::Markdown.new(CustomRender).render(markdown)
~~~

It can certainly be improved and it's certainly not the most secure way to handle these things but you can bring a library like Oga or Nokogiri to make it bullet proof.

As a rule of thumb, we are trying to provide options only when it's a very common behavior or something that can't be easily implemented yourself but the custom render API is generally powerful enough to let you customize things easily.

Have a nice day !
