### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by gghangura** [vmg/redcarpet#667]
Hey,

I am trying to install redcarpet on Mac OS Mojave and this is the error I get. 

Building native extensions.  This could take a while...
ERROR:  Error installing redcarpet:
	ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
make: *** No rule to make target `/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/universal-darwin18/ruby/config.h', needed by `autolink.o'.  Stop.

make failed, exit code 2

Gem files will remain installed in /Library/Ruby/Gems/2.3.0/gems/redcarpet-3.4.0 for inspection.
Results logged to /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-18/2.3.0/redcarpet-3.4.0/gem_make.out

Please help.

**Comment by gghangura** [comment]
updating ruby fixed it

**Comment by jnross** [comment]
I am experiencing the same issue.  @gghangura: how did you update ruby?  I tried installing the latest version using Homebrew and it made a mess of things, and I was unable to run the installed gems.
