### ISSUE TITLE
Redcarpet install issue on Ubuntu

### ISSUE THREAD

**Issue by Manish-Mj** [vmg/redcarpet#674]
Hello Team,

Am unable to install redcarpet. I tried the below commands but still it exits with below error.
Any help is appreciated.

root@host# gem update --system 2.3.0
Updating rubygems-update
..
..
root@host# gem install redcarpet --platform=ruby --verbose
HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=redcarpet
200 OK
/var/lib/gems/2.3.0/gems/redcarpet-3.4.0/COPYING
/var/lib/gems/2.3.0/gems/redcarpet-3.4.0/Gemfile
/var/lib/gems/2.3.0/gems/redcarpet-3.4.0/README.markdown
..
..
..
/usr/bin/ruby2.3 extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h
ERROR:  Error installing redcarpet:
        ERROR: Failed to build gem native extension.

    Building has failed. See above output for more information on the failure.
extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/redcarpet-3.4.0 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/redcarpet-3.4.0/gem_make.out

OS:

NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Comment by 3limin4t0r** [comment]
> mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

Do you have the `ruby-dev` package installed?

**Comment by robin850** [comment]
Hello,

Very late reply here but as @3limin4t0r posted, you might need an additional package for the Ruby headers to be available on your system. The following line in your output might give a hint:

~~~
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h
~~~

I'm giving this a close but feel free to comment if you are still struggling with that and we can reopen.

**Comment by Manish-Mj** [comment]
Thank you @3limin4t0r & @robin850 for the response. Its quiet hard for me to recollect now what happened next. :-)

**Comment by badbabykosh** [comment]
@robin850 having same problem. I'm on a ubuntu system. How do I install these needed headers?
