### ISSUE TITLE
The Ruby Dependency badge is broken

### ISSUE THREAD

**Issue by jrwrigh** [vmg/redcarpet#688]
Both the badge itself isn't rendering and the website itself is not working.

![image](https://user-images.githubusercontent.com/20801821/78150419-83487600-73f4-11ea-99ba-a7e967f19f07.png)

This is displayed when clicking the link:
![image](https://user-images.githubusercontent.com/20801821/78150467-8fccce80-73f4-11ea-9b88-b206eba50f77.png)

**Comment by robin850** [comment]
Hello @jrwrigh,

This has been fixed with https://github.com/vmg/redcarpet/commit/cd1e3c7578718c1029c44859f7a469008be17d91. This badge wasn't very useful anyway as we don't have runtime dependencies.

Thanks for reporting ; I'm giving this a close.
