### ISSUE TITLE
:autolink with nofollow

### ISSUE THREAD

**Issue by docgecko** [vmg/redcarpet#69]
Hello there,

I have a site where users can enter text using markdown, which is then posted to the site.

The text entered by the users may also include email and url links and, as such, I am using the :autolink option to allow them to appear as links in the text.

However, I want these links to be "nofollow" links, but I am unable to find how to do this.  I know this is not specifically an issue, but is there a current way or turning on or off a nofollow option or would some hacking need to be done.  If a hack is required, could you provide a way of doing this?

Many thanks,

Daren

**Comment by abrambailey** [comment]
This is my code, which seems to work
```ruby
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = CustomRender.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
```
