### ISSUE TITLE
Is there a renderer for HTML to Markdown

### ISSUE THREAD

**Issue by sandip-mane** [vmg/redcarpet#694]
Just checking it someone has created it.

**What I want to do**
Add an ability to toggle editor between HTML and MD. I am using TRIX editor(if at all that matters)

**Comment by robin850** [comment]
Hello @sandip-mane,

This project aims at taking Markdown as an input and convert it to whichever format you want (with HTML supported out of the box) but it doesn't work the other way around.

Also, for your particular use case, such round-tripping should certainly be handled on the client-side, thus this library might not be the right tool to do it. There's [an open pull-request](https://github.com/basecamp/trix/pull/737) on the Trix side to support Markdown ; maybe that's something you might be interested in.

Thanks ; I'm giving this a close.
