### ISSUE TITLE
Ampersand in TOC still doesn't render correctly 

### ISSUE THREAD

**Issue by enthusiasmus** [vmg/redcarpet#696]
Hi! 

Thanks for this great gem!

The following test should succeed, but it doesn't. Instead of `#main-bar` the output contains only `#main`. One can use this test to implement the feature. Unfortunately my C skills are kind of rusty.

```
class HTMLTOCRenderTest < Redcarpet::TestCase
  ...
  def test_converting_ampersand_correctly
    markdown = "# Main & Headline"
    output = render(markdown)
    assert output.match("<a href=\"#main-bar\">Main & Headline</a>")
  end
end
```

Would be great!
Best regards,
Lukas

**Comment by robin850** [comment]
Hello @enthusiasmus,

Sorry for the late reply. Indeed, this was a bug on our side due to the fact that HTML entities are stripped out from the generated anchor so dealing with the `&` char requires an extra check. This should be fixed in the next Redcarpet release.

Thanks for reporting !
