### ISSUE TITLE
XSS via svg upload

### ISSUE THREAD

**Issue by odd0introvert** [vmg/redcarpet#712]
Stored XSS is possible by uploading specially crafted SVG via image upload. Here are few screenshots from an application that uses the RedCarpet gem. 

![2021-07-08 20_04_39-New Topic · Homeland](https://user-images.githubusercontent.com/74191364/125073706-fce01100-e0d9-11eb-8516-5334cf64f3b0.png)

![2021-07-08 20_05_02-xss testing · Homeland](https://user-images.githubusercontent.com/74191364/125073721-036e8880-e0da-11eb-9db0-41e9e4b2e920.png)

![2021-07-08 20_05_36-](https://user-images.githubusercontent.com/74191364/125073736-07020f80-e0da-11eb-856a-d54a206276e1.png)

**Comment by mattr-** [comment]
I'm not sure how this is the responsibility of the redcarpet gem to protect against an XSS in your application. Please reopen if you can clarify.
