### ISSUE TITLE
Ruby 3.2.0: warning: undefining the allocator of T_DATA class Redcarpet::Markdown

### ISSUE THREAD

**Issue by mattbrictson** [vmg/redcarpet#732]
I am using Ruby 3.2.0.preview3.

When trying to use redcarpet, I get the following warning.

```
$ irb                                             
>> require "redcarpet"
true
>> Redcarpet::Markdown.new(Redcarpet::Render::HTML.new)
(irb):2: warning: undefining the allocator of T_DATA class Redcarpet::Markdown
```

There is more information on this warning and a suggested fix here: https://github.com/ueno/ruby-gpgme/issues/157

**Comment by mattbrictson** [comment]
Oops, I see this was already fixed in #721. Closing.

**Comment by mattbrictson** [comment]
Could we get a new gem release to fix this? Considering #721 was merged back in April 2022.

**Comment by djrobby** [comment]
@mattbrictson did you ever figure this out?

**Comment by mattbrictson** [comment]
@djrobby yes, for the time being I have to depend on the master branch by putting this in my Gemfile:

```ruby
gem "redcarpet", github: "vmg/redcarpet", branch: "master"
```

**Comment by djrobby** [comment]
@mattbrictson Yeah, that was my first goto solution but it didn't work either. I'm on `ruby-3.2.0`. I guess we'll wait and see. Thank you!

**Comment by unicornzero** [comment]
Could we get a new gem release for this, please?
