### ISSUE TITLE
Need ability to NOT wrap with <p> tags

### ISSUE THREAD

**Issue by andrewhavens** [vmg/redcarpet#92]
I am using redcarpet to take a string like this:

```
My text has some <script>alert('bad stuff')</script> in it
```

and strip out the html. However, the string that I get back is wrapped in `<p>` tags. I know this is probably normal behavior, but this string is going to be going in a `<span>` tag, not a `<p>`.

Is there a way I can `render(text)` without wrapping in a `<p>` tag?

**Comment by bkazez** [comment]
This solution doesn't work if the markdown is a blockquote, like `> test`, since redcarpet puts the `<blockquote>` outside the `<p>`.

**Comment by noahgibbs** [comment]
Yeah. Any solution based on regexps is going to have some blind spots. If you really care (e.g. there might be insecure alert/script tags) then you really, really need to use a sanitiser that parses properly like Nokogiri, Loofah, etc. More work, but a regexp guarantees security leaks :-/
