### ISSUE TITLE
Follow the the HTML5 standard for language hint classes on <code> elements

### ISSUE THREAD

**Issue by ogier** [vmg/redcarpet#93]
The HTML5 standard defines a way to hint that a code block contains syntax of a specific language [[link]](http://dev.w3.org/html5/spec/Overview.html#the-code-element). Redcarpet's code hints are almost identical, except that they don't include the `"language-"` prefix in the class attribute on the `<code>` tag.

For example, the following markdown rendered with `:fenced_code_blocks` enabled

``````
``` python
def foo(bar):
    return bar
```
``````

generates the following HTML:

``` html
<pre><code class="python">def foo(bar):
    return bar
</code></pre>
```

Whereas the standard suggests that it generate:

``` html
<pre><code class="language-python">def foo(bar):
    return bar
</code></pre>
```

Making this change would make Redcarpet's generated HTML more compatible with downstream syntax highlighting and processing, for example [nanoc's colorize_syntax filter](https://github.com/ddfreyne/nanoc/blob/master/lib/nanoc/filters/colorize_syntax.rb). There may be some current highlighters that depend on the current implementation of a plain language name, but in the long term it makes sense for everyone to follow the standard.

**Comment by fengye87** [comment]
I was trying to do the same thing: prefixing "language-" to `<code>` tag's class. So overriding `fenced_codeblocks` callback is the right way to go, but I cannot find this callback method in code base. Has it got removed or did I miss something?

**Comment by robin850** [comment]
@fengye87 : The right method to override is `block_code(code, lang)`; you can find all the callbacks in the [README file](https://github.com/vmg/redcarpet#block-level-calls).

**Comment by krismeister** [comment]
Nice architecture to allow the blocks to be customized.
Here is a gist to use language-xxx:
https://gist.github.com/krismeister/6e33e7c0f4a1f8e4a8708779f253e1ca
